### ISSUE TITLE
Arduino's Stream files

### ISSUE THREAD

**Issue by augustold** [SpenceKonde/ATTinyCore#101]
Hello, is there any reason in particular to not include the [Stream.h](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Stream.h) and [Stream.cpp](https://github.com/arduino/Arduino/blob/master/hardware/arduino/avr/cores/arduino/Stream.cpp) files at this core? Has anyone tried them out?

**Comment by SpenceKonde** [comment]
I have not - I didn't realize that this core didn't have the full version of Stream. 

I don't know if I can switch the versions of stream without breaking other stuff. If you try it before I do, let me know how it goes.
