### ISSUE TITLE
Support remapped SPI pins on x41

### ISSUE THREAD

**Issue by phardy** [SpenceKonde/ATTinyCore#117]
I'm not sure if you want to include this in #57 or not, but thought I'd open a new issue to bring it to your attention.

The `SPIClass::begin` function currently sets SCK and MOSI by doing this

    pinMode(SCK, OUTPUT);
    pinMode(MOSI, OUTPUT);

But that doesn't work if the SPI pins are remapped. I'm currently doing the following to enable [this SPI example sketch](https://learn.sparkfun.com/tutorials/using-the-serial-7-segment-display/example-2-spi) to work with remapped pins:

    REMAP |=  (1<<SPIMAP); // Use the alternative remapped pins for SPI
    SPI.begin();  // Begin SPI hardware
    pinMode(9, OUTPUT); // Set the remapped MOSI pin as output
    pinMode(7, OUTPUT); // Set the remapped SCK pin as output

(sorry, I'm using the Arduino pin mappings because I'm not sure if there are more convenient labels defined for them)

It would be very convenient if `SPIClass::begin` could check the status of the REMAP register and set the right `SCK` and `MOSI` pins.

**Comment by SpenceKonde** [comment]
Will fix alongside Unified-SPI update.
