### ISSUE TITLE
attiny261 digitalPinToPCICRbit(p) mapping

### ISSUE THREAD

**Issue by philbowles** [SpenceKonde/ATTinyCore#119]
The 261 has an "unusual" PCINT pin mapping. From the datasheet it appears that PCINT0-7 and 12-15 are controlled by PCIE1 thus requiring bit 5 to be set in GIMSK and 8-10 by PCIE0 requiring bit 4.

Thus I believe that the following change in pins_arduino.h for the 261 should fix it:

//#define digitalPinToPCICRbit(p) ((((p) >= 0 && (p) <= 2) || ((p) >= 10 && (p) <= 14)) ? 4 : 5)
#define digitalPinToPCICRbit(p) (((p) >= 6 && (p) <= 9) ? 4 : 5) // PMB Hack

I hope I have understood this correctly!

**Comment by SpenceKonde** [comment]
Thanks.
