### ISSUE TITLE
attiny828 pin map issue?

### ISSUE THREAD

**Issue by FERCSA** [SpenceKonde/ATTinyCore#120]
Here is a very simple example:

pinMode(PC7, OUTPUT);
digitalWrite(PC7, HIGH);

When I'm using PC7 it doesn't work, but if I'm using A23 or 23 instead it's okay.
I got the same issue with PC5 too. Maybe the whole PORT C is problematic? I should test my theory.
What should be the problem? Any hint?

**Comment by SpenceKonde** [comment]
You should use the Arduino Pin numbers shown on the pinout chart, not the PXn notation. https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/extras/ATtiny_828.md

The port pin numbers are shown on the chart for reference only - you can't use them with arduino pin manipulation functions. 

The portpins.h file (which is pulled in by the standard Arduino libraries) defined PC7 as PORTC7 - which is just the bit number corresponding to PC7 within the PORTC register, ie, 7. Those defines can be used like: PORTC |=(1<<PC7); that will turn into PORTC|=(1<<7); after the define is replaced.
