### ISSUE TITLE
ATtiny841 pinout incorrect

### ISSUE THREAD

**Issue by stuartsnow** [SpenceKonde/ATTinyCore#127]
Just a quick one: TXD1 and RXD1 are the wrong way round on the ATtiny841 diagram.

**Comment by MCUdude** [comment]
According to the data sheet, PA4 goes to RXD1, and PA5 goes to TXD1. Seems to be correct in the pinout diagram in the readme

**Comment by SpenceKonde** [comment]
Oh - I had the wrong image referenced in the chip-specific doc... Fixed now. Thought I had to fix the image.
