### ISSUE TITLE
Consider renaming IDE platform/board package menu "ATTinyCore"

### ISSUE THREAD

**Issue by bperrybap** [SpenceKonde/ATTinyCore#132]
Currently the name of the platform/board package that shows up in the IDE menu when selecting a board  is:
ATtiny Universal
While it is just a name, I find it confusing since the name doesn't match the name used in the boards manager package which is:
ATTinyCore

In my case it is extra confusing since I have MANY different board packages and cores installed.

The name that shows up in the IDE board selection menu is in the platform.txt file
Currently it is:
name=ATtiny Universal

It would be nice the name used in the board selection menu contained "ATTinyCore" in the name.

**Comment by SpenceKonde** [comment]
That sounds reasonable
