### ISSUE TITLE
Add support for software I2C in unified wire library

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/ATTinyCore#133]
Currently the 841 and 828 still don't work with the unified wire library, because they need software implementation for I2C master, but do have hardware I2C slave. 

So we need a bastardized software-master-hardware-slave library (ideally - failing that, straight software) for these parts.

**Comment by j54n1n** [comment]
I whipped together a version of an I2C software-master and hardware-slave library. See also #140. I've not yet tested all cases so be beware.

**Comment by SpenceKonde** [comment]
Thanks - setting to awaiting verification
