### ISSUE TITLE
PWM issue on 167

### ISSUE THREAD

**Issue by Tada9** [SpenceKonde/ATTinyCore#146]
Hi, 
few years ago there was this issue [https://github.com/SpenceKonde/ATTinyCore/issues/37](https://github.com/SpenceKonde/ATTinyCore/issues/37) regarding secondary timers being off by default and therefore only one PWM chanel was working.
The same applies for x7  and presumably many other. The same issue with the same solution, but the fancy option menu is nowhere to be found. After few hours of troubleshooting I managed to solve this by editing my pins_arduino.h file, but I don't think this should be the way to go.

PS. It could probably be on by default, since flash is not really a bottleneck on these chips.

**Comment by SpenceKonde** [comment]
Thanks, fixed it with 64a17f7d4526a5d2b22231ca9bb013401a3f4a48 and a90ae6ea3b08be8bb785b2152e70c12275423667

That was the only one that I missed that on, I think.
