### ISSUE TITLE
No update in Arduino Boards Manager for v1.1.3?

### ISSUE THREAD

**Issue by beicnet** [SpenceKonde/ATTinyCore#149]
Hello @SpenceKonde 

I saw that you released the ATTinyCore v1.1.3, but there is no such version in Arduino IDE Board Manager, can you please fix that?

Kind regards,
Viktor

**Comment by SpenceKonde** [comment]
The process of updating board manager involves multiple people and is ongoing, please be patient, it will be ready within a day

**Comment by beicnet** [comment]
@SpenceKonde Okay!
