### ISSUE TITLE
Latest release (v1.4.0) doesn't contain the avr folder

### ISSUE THREAD

**Issue by MCUdude** [SpenceKonde/ATTinyCore#159]
FYI the *avr* folder is missing from the ZIP-file. I wonder if this applies to the boards manager as well?
<img width="611" alt="skjermbilde 2017-08-06 23 28 22" src="https://user-images.githubusercontent.com/3238730/29007250-123b31be-7aff-11e7-94e9-62f70e11ee23.png">

**Comment by SpenceKonde** [comment]
The .zip files in the releases are for installation via board manager - they don't work with manual installation. They have the folder structure for board manager, not manual installation. For manual installation, sync the repo into hardware or download the repo (master) as .zip, or manually correct the folder structure.
