### ISSUE TITLE
USART in SPI mode ? 

### ISSUE THREAD

**Issue by alessio31183** [SpenceKonde/ATTinyCore#167]
I tried to push the USI as SPI master to fclk/2 with this function:

#define MOSI PB2   //DI
#define SCK  PC1
#define SS   PA6  //chip select

void enable_spi(unsigned char speed)
{
    if (speed) {
        speed--;
        PORTA |= (1<<SS);       // pull-up i.e. disabled
        DDRA |= (1<<SS);        // HIGH state
        DDRB |= (1<<MOSI);
        DDRC |= (1<<SCK);
        USICR = (1<<USIWM0)|(1<<USICS1)|(1<<USICLK);
        PORTA &= ~(1<<SS);    // enable Slave
    } else {
        PORTA |= (1<<SS);     // pull-up i.e. disabled
        DDRA &= ~(1<<SS);     // LOW state
        DDRB &= ~(1<<MOSI);
        DDRC &= ~(1<<SCK);
        USICR = 0;
    }
}

unsigned char spi_500Khz(unsigned char val)
{
    USIDR = val;
    USISR = (1<<USIOIF);   //resets counter, clears flag
    do {
        USICR = (1<<USIWM0)|(1<<USICS1)|(1<<USICLK)|(1<<USITC);
    } while ((USISR & (1<<USIOIF)) == 0);
    return USIDR;
}

unsigned char spi_4Mhz(unsigned char val)
{
    USIDR = val;
    USISR = (1<<USIOIF);
    uint8_t reg = (1<<USIWM0)|(1<<USICS1)|(1<<USICLK)|(1<<USITC);
    USICR = reg;
    // asm volatile ("nop");
    USICR = reg;
    // asm volatile ("nop");
    USICR = reg;
    // asm volatile ("nop");    
    USICR = reg;
    // asm volatile ("nop");
    USICR = reg;
    // asm volatile ("nop");
    USICR = reg;
    // asm volatile ("nop");
    USICR = reg;
    // asm volatile ("nop");
    USICR = reg;
    // asm volatile ("nop");
    USICR = reg;
    // asm volatile ("nop");    
    USICR = reg;
    // asm volatile ("nop");    
    USICR = reg;
    // asm volatile ("nop");    
    USICR = reg;
    // asm volatile ("nop");    
    USICR = reg;
    // asm volatile ("nop");    
    USICR = reg;
    // asm volatile ("nop");    
    USICR = reg;
    // asm volatile ("nop");    
    USICR = reg;
    // asm volatile ("nop");
    return USIDR;
}

If you want to reduce the speed of twice just put the asm volatile ("nop") in the between each USICR

Thanks

**Comment by SpenceKonde** [comment]
Closing this issue, but referencing it from the issue relating to USI clock rates. 

It's falling into place, though I'm worried about the impact on code size.... In order to make this work with the standard API, the speed would have to be selectable at runtime, meaning that all of the different-speed functions would get compiled in regardless of which were used.
