### ISSUE TITLE
Allow for external oscillators at UART optimized frequencies for 4313

### ISSUE THREAD

**Issue by jbebel** [SpenceKonde/ATTinyCore#173]
I'm interested in using a 4313 for serial communication at 115200, and in order to do that reliably, I have an 11.0592 MHz oscillator. Unfortunately, that's not an option when I select the 4313.  I'm sure this applies to other MCU's as well, and all the UART optimized frequencies would be good to include.

**Comment by SpenceKonde** [comment]
Huh, looks like I didn't include the UART crystals on the x313 chips. 

Will do alongside the other boards.txt improvements planned for 1.1.5

**Comment by jbebel** [comment]
I added a comment to the change. Not sure about the other chips, but the x313 needs 0xFD in the low fuses for external 3-8 MHz oscillators.
