### ISSUE TITLE
How to use the PCINT1 on ATtiny1634

### ISSUE THREAD

**Issue by alessio31183** [SpenceKonde/ATTinyCore#178]
Dear all,
I'm trying to use the PCINT1 on ATtiny1634
What I've done is to enable the interrupt in the setup:

  SREG |= (1 << SREG_I);    // Enable global interrupts 
  GIMSK |=  (1<<PCIE0);    // Enable pin change interrupt for PCINT[7:0] on PCINT0
  PCMSK0 =  (1<<PCINT1); 

and then to define the interrupt function as:

ISR(PCINT0_vect)       // interrupt service routine called when PCINT1 changes state 
{
....
}

Hope to be usefull for someone else

**Comment by alessio31183** [comment]
No sorry I've got problem but solved later on.
I had written the issue before to solve it.
You can close it.

Thanks

**Comment by SpenceKonde** [comment]
Great, glad to hear it's working for you :-)

**Comment by colesnicov** [comment]
@alessio31183  Do you want to share a resume?
