### ISSUE TITLE
digitalPinToInterrupt for ATTINY4313 is not working. (solution proposal)

### ISSUE THREAD

**Issue by ortegafernando** [SpenceKonde/ATTinyCore#179]
Hi, i think this line in pin's definitions of ATTINY4323

#define digitalPinToInterrupt(p)  ((p) == 5 ? 0 : ((p)==4?1: NOT_AN_INTERRUPT))

should be:

#define digitalPinToInterrupt(p)  ((p) == 5 ? 1 : ((p)==4? 0: NOT_AN_INTERRUPT))

Thanks

**Comment by SpenceKonde** [comment]
Thanks for reporting! I don't use the x313 chips due to the small flash, and testing of the new unified SPI/I2C libraries has been pretty sparse in general, so I really appreciate that others are keeping tabs on this.

**Comment by ortegafernando** [comment]
Thanks for you for maitaining this core.
