### ISSUE TITLE
`SPI.transfer(buffer, size)` doesn't work

### ISSUE THREAD

**Issue by exzombie** [SpenceKonde/ATTinyCore#180]
Hi!

I've been testing SPI on ATtiny84 with a LoRa module. [The docs for the SPI library](https://www.arduino.cc/en/Reference/SPI) state that `transfer(buffer, size)` overwrites `buffer` with received data which doesn't happen here. Or rather, the first byte it sends works, as far as I can see with a logic analyzer. After the first byte and on subsequent transfers, DO seemingly changes polarity and SCK remains low. The data in `buffer` is untouched.

**Comment by SpenceKonde** [comment]
Thanks for reporting this.

**Comment by SpenceKonde** [comment]
To expedite fix, please post code that reproduces this issue, but which works when compiled for something with real SPI instead of a USI.

**Comment by exzombie** [comment]
I would, but I don't have a 3V device with hardware SPI available. I'll try to obtain one soonish to confirm what the correct behaviour is. In the meantime, I'll take a look at the code, with an eye towards #134; no promises though :) as my free time comes in short bursts.

**Comment by exzombie** [comment]
Still waiting for a 3V device. But I've looked at the code and decided that I won't try to debug it. Instead, I'll rewrite it because I also found that the data order setting is only honored for `transfer(uint8_t)`; I'll fix that to match the hardware SPI version, i.e. this setting should change both bit and byte order.
I've looked at #167 where you expressed your concern about code size. So yeah, a version of the USI clocking code has to be generated for each clockdiv provided by the API. I can put it in the `.cpp` file, where it will always be available; it will increase code size, but LTO should remove unused code. Or, I can put it in the `.h` file, where only the code actually used will be instantiated, LTO or not. What do you think?
