### ISSUE TITLE
Typo in ATtiny_x4.md

### ISSUE THREAD

**Issue by JChristensen** [SpenceKonde/ATTinyCore#185]
In the file avr/extras/ATtiny_x4.md, under "Tone Support", I think PB1 should be PB2. For clarity, I might also change "2 and 4" to "4 and 2" so that it reads:
`Tone() uses timer1. For best results, use pin 6 and 8 (4 and 2 with alternate pinout - PA6 and PB2), as this will use the hardware output compare to generate the square wave instead of using interrupts.`

**Comment by SpenceKonde** [comment]
Fixed. On the tinyx4 the "good" tone pins are PA5 and PA6, the OC1B, OC1A pins. Somehow an entirely wrong pin snuck in there.
