### ISSUE TITLE
Any chance of supporting ATTINY814

### ISSUE THREAD

**Issue by whmountains** [SpenceKonde/ATTinyCore#189]
Is there any technical limitation preventing ATTinyCore from being ported to this MCU?  It has some nice low-power features that I'd like to use.

**Comment by SpenceKonde** [comment]
Duplicate of #174. 

Supporting these chips requires rewriting every single function that inferfaces with chip features in any way - serial, digitalWrite/Read/pinMode, PWM, SPI, I2C, and so on - EVERYTHING. These parts might as well be a different architecture entirely.

**Comment by SpenceKonde** [comment]
https://github.com/SpenceKonde/megaTinyCore This is happening now. Still not quite ready, but progressing quickly, follow that repo for updates
