### ISSUE TITLE
Support for the newer(?) 16x series (1614, 1616, 1617)?

### ISSUE THREAD

**Issue by toddzebert** [SpenceKonde/ATTinyCore#190]
I've had a lot of success using this lib on the ATtiny85's, and now have moved up to these 16x's.

http://www.microchip.com/wwwproducts/en/ATTINY1614

Thanks!

**Comment by SpenceKonde** [comment]
Duplicate. Closed. https://github.com/SpenceKonde/ATTinyCore/issues/174
I am getting REALLY sick of explaining to people, over and over, that I do not have time to rewrite EVERY SINGLE FUNCTION OF THE CORE to support the new PIC-like ATTinys. EVERYTHING is different, they might as well be a different architecture. 

If you want to work on this project, I'd be happy to work with you to get them added, but there's just a huge amount of work to do to reimplement all of the standard arduino libraries, and I have my hands full with my current commitments.

**Comment by toddzebert** [comment]
OK, got it. That issue didn't come up when I searched on variations of these models. Again, thanks for all your effort.

**Comment by SpenceKonde** [comment]
https://github.com/SpenceKonde/megaTinyCore This is happening now. Still not quite ready, but progressing quickly, follow that repo for updates
