### ISSUE TITLE
Definition of C++ keywords

### ISSUE THREAD

**Issue by Floessie** [SpenceKonde/ATTinyCore#193]
Hi Dr. Azzy,

When searching for a `#define` to determine the use of your core (found it: `AT_TINY_CORE`), I stumbled upon the definition of `true` and `false` in [`Arduino.h`](https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/cores/tiny/Arduino.h#L29). This definition is at least missing a `#ifndef __cplusplus`. It is not present at all in stock Arduino.

Best,
Flössie

**Comment by SpenceKonde** [comment]
Re: defines for identifying core: https://github.com/SpenceKonde/ATTinyCore/blob/master/Internals.md

Will look into issue in Arduino.h
