### ISSUE TITLE
Boards menu

### ISSUE THREAD

**Issue by MCUdude** [SpenceKonde/ATTinyCore#202]
Is there an idea to reduce the number of available boards in the boards menu by moving the bootloader option inside the specific option? It would make the boards menu go from this:
  
<img width="296" alt="skjermbilde 2018-02-17 11 16 23" src="https://user-images.githubusercontent.com/3238730/36340090-eca3ff02-13d4-11e8-8e03-4dcee6403d4a.png">
  
.. To this:
<img width="297" alt="skjermbilde 2018-02-17 11 21 15" src="https://user-images.githubusercontent.com/3238730/36340094-f6ae0362-13d4-11e8-9eab-d4d6468b9b0d.png">

I think this should be doable with some advanced binary magic.

**Comment by SpenceKonde** [comment]
Sure - this is a low priority though.

**Comment by sleemanj** [comment]
Example implementation in my distribution for reference... 

https://github.com/sleemanj/optiboot/blob/master/dists/diy_attiny/avr/boards.txt#L118

**Comment by SpenceKonde** [comment]
I'm not sure how to do this, because we need the options on the bootloader menu to depend on which chip is selected.... (for example, we need the max upload size to depend on whether a bootloader is selected AND which size chip is selected.....

**Comment by SpenceKonde** [comment]
Closed because doesn't appear to be possible (without a separate entry for each part instead of each family - which would offset any gains in terms of cleaning up the boards menu)
