### ISSUE TITLE
Add support for ATTiny43

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/ATTinyCore#207]
Support for the ATTiny43 has been requested. This is a pretty boring 4k flash ATTiny, but it has the added feature of an on-chip boost converter (just-add-inductor-and-caps) for running off a single alkaline cell and generating 3v for external devices, albeit at very limited current. 

Should just require a variant file and boards.txt entry, nothing special.

**Comment by SpenceKonde** [comment]
Oh - and this does need a bit more work than just a variant defined, because it's timer1 is an 8-bit one (copy of timer0) - I don't think it will work out of the box to get PWM out of timer1 (nor tone() )

**Comment by tedder** [comment]
I'm working on a board design for this, if you manage to get this going I'll send you one.

**Comment by SpenceKonde** [comment]
That's great! I look forward to it. How soon? Maybe I won't have to make one myself to test this! 

If you'd like to talk about the design of the board, have a second pair of eyes look over it before you sent it to the fab house, I'd be happy to take a look. email me spencekonde@gmail.com.

**Comment by tedder** [comment]
I'll drop it your way. Hoping to order parts and send the boards off this
week, i'll be gone until ~jun10 so there'll be time for the parts to arrive.

**Comment by tedder** [comment]
[you've got mail] in case you didn't see it.

**Comment by SpenceKonde** [comment]
Quick note during review here - this will require routines to deal with the lameass 8-bit timer1. This may also be usable for the attiny26.

**Comment by tedder** [comment]
interesting that you brought this up, I just ordered a new board for this.

**Comment by SpenceKonde** [comment]
Don't get too excited, it doesn't mean I was working on it ;-) - I just looked at this and was like "wait, does that thing have a normal timer1?" - no, no it does not.

**Comment by tedder** [comment]
Oh, no worries. I want to get a board working with a hello world LED in AVR and then I'll be anxious. I'll send you a populated board once I know it works.

**Comment by SpenceKonde** [comment]
ToDo list here:
* Create pins_arduino,h for tiny43 variant
* Add support for adjusting CKDIV in init() for 4MHz operation off internal boost converter
* Implement PWM on 8-bit timer1
* Implement Tone on 8-bit timer1?

**Comment by SpenceKonde** [comment]
Preliminary support is in. It *may* be totally working. 

PWM, Tone, SPI, and I2C need to be tested.

**Comment by SpenceKonde** [comment]
If problems, please create new issue. Closing to clean up issues.
