### ISSUE TITLE
Tiny167 (and maybe others) - hardware serial doesn't have readString and other new stream features

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/ATTinyCore#217]
http://forum.arduino.cc/index.php?topic=549316.msg3752370#msg3752370

Unclear why this is the case, since the version of Stream looks correct....

**Comment by SpenceKonde** [comment]
Adding help wanted tag - anyone have any idea what is wrong that's causing HardwareSerial to not have the Stream functions?

**Comment by per1234** [comment]
Problem was caused by the use of an outdated version of ATTinyCore:
http://forum.arduino.cc/index.php?topic=549316.msg3753382#msg3753382
