### ISSUE TITLE
Failing documentation for changing clock speed, etc. in  README.md

### ISSUE THREAD

**Issue by avandalen** [SpenceKonde/ATTinyCore#219]
There is no documentation in  README.md of how to change the clock speed and B.O.D. etc. for the ATTiny (this is done by Tools > clock:)

**Comment by SpenceKonde** [comment]
Thanks. I've added some details. As I've said before (many times, in many places) I'm not good at writing documentation - I don't know what will and won't be obvious to my users. I have open issues flagged "help wanted" for documentation and examples.
