### ISSUE TITLE
No support for F() macro

### ISSUE THREAD

**Issue by hansibull** [SpenceKonde/ATTinyCore#22]
I tried to compile code that contained the line:
Serial.println(F("Hello World!"));

.. and got an error:
/Users/hansi/Documents/Arduino/hardware/ATTinyCore_12-09-15/avr/cores/tiny/Arduino.h:221:0,
                 from sketch_sep13a.ino:1:
sketch_sep13a.ino: In function 'void loop()':
/Users/hansi/Documents/Arduino/hardware/ATTinyCore_12-09-15/avr/cores/tiny/WString.h:41:88: error: reinterpret_cast from type 'const char*' to type '__FlashStringHelper*' casts away qualifiers
 #define F(string_literal) (reinterpret_cast<__FlashStringHelper *>(PSTR(string_literal)))
                                                                                        ^
sketch_sep13a.ino:7:17: note: in expansion of macro 'F'
Error compiling.

Is this something that may be implemented?

**Comment by SpenceKonde** [comment]
This is a bug, I thought the F() macro was working. I'll try to figure out what's going on here, thanks for reporting.
