### ISSUE TITLE
Some bootloaders look like they are wrong...

### ISSUE THREAD

**Issue by WestfW** [SpenceKonde/ATTinyCore#232]
I ported some of this code over to https://github.com/Optiboot/optiboot/blob/master/optiboot/bootloaders/optiboot/Makefile.tiny (not really tested yet, BTW) and noticed a few things that seem to be wrong.  (also, you might want to make use of the new makefile features!)

attiny167at12 has suspicious section_start values.

attiny841at184 has wrong UART ?

oops - the other one I thought I notice was my fault...

**Comment by SpenceKonde** [comment]
Thanks!

**Comment by SpenceKonde** [comment]
The section addresses were only correct for the 167 at 12 - all the other 167 ones were wrong. Copy/paste error from 87, went unnoticed because I didn't upload anything bigger than 8k in testing.
