### ISSUE TITLE
Attiny differenses? ssn ssu su etc?

### ISSUE THREAD

**Issue by sixtemesseven** [SpenceKonde/ATTinyCore#233]
Hi

I read the wiki since I was interested in what specific IC I should buy. I'm particularly interested in the Attiny25 variant in a soic8 package. The cheapest one @ farnell seems to be the Attiny25-20ssn. I searched the datasheet for the term ssn but I couldn't find a reference to what the ssn part actually means?

Maybe somebody could help me and I put the information into the wiki?

Regards
Andreas

**Comment by SpenceKonde** [comment]
Table 25.1 in the datasheet lists all of the atmel part numbers, and shows the differences between them. Those last letters describe the package and operating temperature range of the part per that table. SSN is a narrow SOIC-8 package spec'ed for operation between -40C and 105C, for example. 

Note also that SOIC-8 does not describe a single package footprint - it comes in two widths (see the package descriptions below table 25.1 of the datasheet, or the digikey dimensions column, where atmel translates between the arbitrary and non-standard names for the packages and the industry standard ones, including listing the two widths and which standards body they're associated with)

Which wiki are we talking about, by the way?
