### ISSUE TITLE
Release v1.1.5 Arduino Board Manager error

### ISSUE THREAD

**Issue by seurat-atreides** [SpenceKonde/ATTinyCore#235]
Hi,

the https://github.com/SpenceKonde/ATTinyCore/archive/1.1.5.tar.gz file can't be downloaded and the Arduino Board Manager time out.

**Comment by SpenceKonde** [comment]
File downloads fine for me; this is an issue with your network connection (for example, not connected to internet, or connection is filtered/blocked by software on your computer (possibly firewall/security/program control type software) or at a network level by your network administrator) - or it was a transient problem with the github file servers which is now resolved.
