### ISSUE TITLE
ATtiny85 Serial at 1Mhz ?

### ISSUE THREAD

**Issue by nagaokashi** [SpenceKonde/ATTinyCore#247]
Thank you for great source.
I did a program on ATtiny85, transceive data from/to BLE with 8Mhz internal. Everything works fine.
Now I want to optimize power, I changed to 1Mhz internal. But it did not work.
(Tone() also sound strange from 8Mhz)
So, my question is Do I need to change any other setting to get program work when changed from 8Mhz to 1Mhz?

**Comment by sleemanj** [comment]
You must burn bootloader when you change the speed in order to set the fuses.

**Comment by nagaokashi** [comment]
@sleemanj  Thanks again. I'll try and feedback.

**Comment by nagaokashi** [comment]
It works.
Thank you.
