### ISSUE TITLE
ATtiny861 compile error

### ISSUE THREAD

**Issue by nopnop2002** [SpenceKonde/ATTinyCore#254]
![tiny861-1](https://user-images.githubusercontent.com/6020549/47290748-e8af0980-d63b-11e8-9e6b-e8c8b062b953.jpg)

I added one line to board.txt

attinyx61.build.core=tiny

It's fixed.

**Comment by coryk88** [comment]
Having this same issue, also now unable to burn bootloader on MacOS

**Comment by SpenceKonde** [comment]
Thanks, it is now fixed in the github version. This was a serious regression - while adjusting the boards.txt for 1.2.0 improvements, I must have accidentally highlighted an extra line and deleted it.
