### ISSUE TITLE
 ISR (WDT_vect) does not work in ATtiny167 when WDT is enabled

### ISSUE THREAD

**Issue by vsv78vrn** [SpenceKonde/ATTinyCore#260]
ISR (WDT_vect) does not work in ATtiny167 when WDT is enabled. The interrupt bit set. Interrupt allowed. I tried a bunch of code from the Internet. BUT! On ATtimy85 everything works.

**Comment by vsv78vrn** [comment]
I use optiboot as a bootloader

**Comment by SpenceKonde** [comment]
Are you using the latest version of the bootloader? This was a known issue
with the virtualboot funtion - on attiny, there is no hardware bootloader
(BOOTRST) functionality, so the bootloader rewrites the vector table and
puts the reset vector in place of one of the other vectors (and the address
of the bootloader in place of reset vector, so bootloader runs on
reset/startup), and jumps to that to start the program. Until ATTinyCore
1.2.0, this used the wdt vector, so the wdt could not be used as an
interrupt source. As of 1.2.0 (released just a few weeks ago), the
bootloader was updated to use the almost totally unused EE_RDY vector
instead.

Connect to ISP programmer and do burn bootloader with the latest version of
ATTinyCore , and it *should* work.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by vsv78vrn** [comment]
c:\Users\Viking\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.2.1\bootloaders\optiboot\
>>> 1.2.1 <<<

**Comment by vsv78vrn** [comment]
Yes, thank you so much, it all worked! Yes, in the place with the update, you also need to sew a new bootloader.

**Comment by SpenceKonde** [comment]
Glad it's working!
