### ISSUE TITLE
128KHz breaks delay()?

### ISSUE THREAD

**Issue by WereCatf** [SpenceKonde/ATTinyCore#263]
I'm not entirely certain if I'm just doing something wrong or if I've misunderstood something, but my Attiny85 seems to crash/stall if I call delay() when using internal 128KHz clock. Absolutely nothing happens after I've issued delay(1) or any other value.

**Comment by sleemanj** [comment]
The minimum clock speed is probably 1MHz if you want
millis/micros/delay/delayMicroseconds to be sensible... 

https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/cores/tiny/Arduino.h#L66


https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/cores/tiny/wiring.c#L218


https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/cores/tiny/wiring.c#L410


With that said, I would have thought it would work, just take about 10
times longer than expected (delay(1) would be more like delay(10))

**Comment by sleemanj** [comment]
[delay() uses micros() to
calculate](https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/cores/tiny/wiring.c#L276)


Using millis() and a spin wait might be accurate enough for you, in
which case you could simply create your own delay function 

    void myDelay(uint32_t howLong)
    { 

      uint32_t start = millis();
      while((millis() - start) < howLong)  /* NOP */;
      return; 

    }

**Comment by WereCatf** [comment]
@sleemanj Yeah, I am already using a millis()-based workaround. I just decided to raise an issue with other people in mind; even if this never got fixed, at least it's documented now.

**Comment by SpenceKonde** [comment]
Which part is this? There are two cores included in this package depending
on which attiny is in use.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by WereCatf** [comment]
@SpenceKonde Ah, I forgot to mention: I am using an ATTiny85.

**Comment by SpenceKonde** [comment]
Why is micros() giving wrong answers? (that's the only way that delay() should fail here)
Shouldn't this work? 

`#if F_CPU < 1000000L
return ((m << 8) + t) * MillisTimer_Prescale_Value * (1000000L/F_CPU);
#else`

**Comment by SpenceKonde** [comment]
Nevermind, I did it. 

But micros() looks close to correct......

**Comment by SpenceKonde** [comment]
I'm baffled, delay *ought* to be working!

**Comment by SpenceKonde** [comment]
AAHA! 
If it jumps more than 1 ms on the last run through the inner loop, it would roll over ms! 
Added a failsafe against that, since it could happen in other cases under extenuating circumstances. At least now delay won't be a permahang if that ever happens. 
For sub-1MHz clock speeds, delay() will now use millis() based implementation.
