### ISSUE TITLE
Pin mapping image issue - OC1A on x61 marked OC0A

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/ATTinyCore#265]
There is no PWM from timer0 on tiny x61. The three PWM channels available are OC1A, OC1B, OC1D. Currently, the pin with OC1A on it is marked OC0A.

**Comment by SpenceKonde** [comment]
@MCUdude

**Comment by MCUdude** [comment]
On the case!

**Comment by MCUdude** [comment]
[ATtiny.zip](https://github.com/SpenceKonde/ATTinyCore/files/2630628/ATtiny.zip)

I still have the ATtiny43 pinout left

**Comment by SpenceKonde** [comment]
Wonderful! Thanks <3 will update the images and close this issue tonight.
