### ISSUE TITLE
ADC Reference 

### ISSUE THREAD

**Issue by smartroad** [SpenceKonde/ATTinyCore#275]
Hi, not an issue, but I have been looking for an answer but not found one that makes sense to me ;) How do I set the ADC reference to 1.1V? I can't figure out how.

**Comment by SpenceKonde** [comment]
Just do:
analogReference(INTERNAL); 

(in place of INTERNAL, you can use any of the options listed in the part-specific documentation page for the part you're using - not all boards have the same options)

**Comment by SpenceKonde** [comment]
Closing because not an issue with the core, feel free to comment if you have additional questions about this.

**Comment by cms-codes** [comment]
It varies depending on the particular MCU, but usually involves setting
certain bits in the ADC register.

I'd suggest checking out the datasheet for the target hardware you're
using. Microchip/Atmel's documentation is well laid out and you should be
able to find details on the internal reference.

**Comment by SpenceKonde** [comment]
@cms-codes - that won't work if using the analogRead() to read it; use analogReference() like I said above. This is the same as the official arduino core. Setting the reference via the registers will get set back to what was last set with analogReference() (or the default reference, Vcc if it hasn't been set already) the moment you call analogRead().

**Comment by cms-codes** [comment]
Right. I am used to going about this directly rather than using the
analogRead() function. Apologies for the confusion.
