### ISSUE TITLE
tinyX61 SPI pins are mixed up

### ISSUE THREAD

**Issue by targodan** [SpenceKonde/ATTinyCore#282]
In the [tinyX61 variant file](https://github.com/SpenceKonde/ATTinyCore/blob/53b203fb8388acd7dc80e597b9f361b1127fb4f5/avr/variants/tinyX61/pins_arduino.h#L53) the DI and DO pins are mixed up. According to the [datasheet](http://ww1.microchip.com/downloads/en/devicedoc/atmel-2588-8-bit-avr-microcontrollers-tinyavr-attiny261-attiny461-attiny861_datasheet.pdf) PB0 is DI and PB1 is DO. You've got it mixed up.

**Wrong:**
```cpp
#define DO_DD_PIN DDB0
#define DI_DD_PIN DDB1
```

**Right:**
```cpp
#define DO_DD_PIN DDB1
#define DI_DD_PIN DDB0
```

This leads to nasty failure of any SPI communication. I tested it on my attiny861a and have had successful communication with my version (right) whereas the communication was unsuccessful without the fix.

Edit: My test was in SPI master mode. Slave mode is of course the other way around but as the comment in the file states it should be configured for master mode.
Maybe a compile flag such as `SPI_SLAVE_MODE` might help in giving the user a chance of getting slave mode working without having to fiddle in the core.

**Comment by targodan** [comment]
I just opened a pull request fixing this.

**Comment by SpenceKonde** [comment]
Much thanks for not only reporting this, but providing a PR!
