### ISSUE TITLE
ATTiny85 QFN Package support

### ISSUE THREAD

**Issue by elgranshaman** [SpenceKonde/ATTinyCore#291]
Hello,

Sorry if this question has already been asked. Is the library compatible with the ATTiny85 in a QFN or MLF package?

Pin functions are the same, but pin number different (physically). 

Thank you

**Comment by SpenceKonde** [comment]
Yes, it is fully compatible with the chips listed as supported, regardless of what package they are in. I don't supply pinout charts for the obscure packages, so you'll have to consult the datasheet to see which physical pin matches with a given logical pin, but there are no other differences between the chips, and everything will just work.

**Comment by elgranshaman** [comment]
Thank you!
