### ISSUE TITLE
Disable TX or RX pin on Attiny841

### ISSUE THREAD

**Issue by tmortonorr** [SpenceKonde/ATTinyCore#307]
IDE: 1.8.5
AttinyCore: v1.2.3
Windows 7: x64
Chip: Attiny841
 
Hi,

I'm trying to disable the Rx pin on Attiny841 by using the command: 'UCSRB0 &=~(1<<RXEN0);' however the compiler says 'UCSRB0' is not declared. Is a library inclusion required that declares this variable? I can alter MCUSR without including any library so thought it would be the same for UCSRB.

Thanks

**Comment by SpenceKonde** [comment]
Thanks for reporting this. I had made a typo in the register name - it is UCSR0B not UCSRB0. I have corrected the documentation. Also sorry for the slow response - things have been busy on my end lately.
