### ISSUE TITLE
Optiboot not available at 1MHz

### ISSUE THREAD

**Issue by ideaalab** [SpenceKonde/ATTinyCore#310]
Is it possible to set the fuses so the Attiny84 can run with the 128 kHz internal oscillator?
For low power/low speed applications this can save some uA.
Thanks!

**Comment by sleemanj** [comment]
In my fork ( https://github.com/sleemanj/optiboot/blob/master/dists/README.md#attiny ) you can choose the 128kHz oscillator from the "Tools > Override Clock Source" menu and then burn bootloader to set the fuses for it.

**However** generally speaking below 1MHz or below things may not work and I would not recommend it, even if the rest of the code was OK with running that slow the 128kHz oscillator is not likely to be anything close to accurate.

Better in my opinion to run at a reasonable speed and just go to sleep as deep and as much as possible - my [SimpleSleep Library](https://github.com/sleemanj/SimpleSleep) makes sleeping, err, simple.

**Comment by ideaalab** [comment]
Thanks!  I will try your fork :)
Do you know if @SpenceKonde is willing to merge your oscillator configurations into AttinyCore?
My code just turn on and off some LEDs according to some switches. Accuracy of timing is not really needed. Your sleep library looks very nice!

**Comment by ideaalab** [comment]
By the way, ive just checked the ATtiny84 datasheet, and 8Mhz consume more than 10 times more current than 1Mhz. And 1Mhz is about 5 times more than 128khz (quick glance at the active supply current on the datasheet)

**Comment by SpenceKonde** [comment]
Thanks for reporting this issue. 128kHz was supposed to be supported for an option with all ATtiny devices that support it (for non-optiboot configurations). Some chips only have a 32kHz ULP. Apparently when I added support for it though, I only added it to the x5 series. It is now available on all parts. I have just added support for it (you'll have to uninstall the board manager version, and install the github version to use it before the next release - I use git to sync the repo to a folder in hardware)

**Comment by freemovers** [comment]
For switching LED's based on some switches I would use the interrupt pin (int0) and keep the ATtiny in sleep mode the rest of the time. If you don't want, or you can not use the int0 pin, you can still check the status of the pins every 100ms or so by using the WDT (which is running on the 128kHz oscillator), or use the Simple Sleep library above (I'm sure that is using the WDT as well). As you can see from the datasheet the sleep mode will only use 4μA in sleep mode with the WDT enabled, the 128kHz oscillator about 50μA (at 3V) and the 1MHz around 500μA (but you would only run it at 1MHz for some microseconds when using the sleep mode).

**Comment by SpenceKonde** [comment]
Agree @freemovers - though I would use PCINTs - he says "switches" not "switch", so the ability to use PCINTs on more pins would make implementation easier. Could probably just have an empty ISR and have the chip check the switch status when it wakes up...

**Comment by ideaalab** [comment]
Thanks for your approach ideas!
This time i think it will be enough simply by reducing oscillator speed. I know i can cut down further if i go to sleep, but will make the code a little bit more complicated, and i want to keep it straightforward for this project, as it will not be mainteined by me, but by others. So better not to trust in their knowledge :)

**Comment by ideaalab** [comment]
> you'll have to uninstall the board manager version, and install the github version to use it before the next release

Instead of uninstalling is it possible to just overwrite the boards.txt file with the new one?

**Comment by SpenceKonde** [comment]
Oh - and when I talked about a manual install into hardware, I mean the hardware folder in your sketchbook folder (you may need to create it), not the hardware folder under the IDE install location, which should never be modified. See https://github.com/SpenceKonde/ATTinyCore/blob/master/Installation.md

That said, modifying the boards.txt of an installed board manager package would probably work - though I generally don't recommend digging around in installed board manager packages and modifying them. 

The boards.txt for packages installed via board manager is buried somewhere under the Arduino15 folder (I forget the directory structure within Arduino15, but ones you're there it's straightforward to find):
On Mac OS X:
/Users/(username)/Library/Arduino15

On Windows:
C:\Users\(username)\AppData\Local\Arduino15
(note that AppData is a hiden folder)

On Linux:
/home/(username)/.arduino15    (a.k.a. ~/.arduino15)

**Comment by ideaalab** [comment]
Hi!
While waiting for next release to include the missing oscillation speeds, ive simply overwritten the boards.txt
Now 128Khz is showing for Attiny24/44/84, but its not showing for Attiny44/84 (optiboot).
I think it must be added.
Additionally, i would change the order of the list. And would place all "internal" options on top. Now its 8Mhz internal at the top of the list, and 128Khz internal at the bottom of the list, with all the external options in between.
Just a suggestion...

**Comment by SpenceKonde** [comment]
I dont provide oscillator clock sources slower than 1MHz for optiboot configurations. At 128 kHz, youre looking at 600 baud for the bootloader, which is slow enough that problems

**Comment by ideaalab** [comment]
1Mhz is not showing either for **Attiny44/84 (optiboot)**

**Comment by SpenceKonde** [comment]
That should be fixed.

**Comment by SpenceKonde** [comment]
Also worth noting that the makefile is missing a shitload of entries... I sure hope I have a clean copy of it at home.
