### ISSUE TITLE
EEPROM are not being retained after loading a sketch

### ISSUE THREAD

**Issue by jhmluna** [SpenceKonde/ATTinyCore#312]
Hello.

This is the first issue I open, so please forgive me if I am not following some procedure.
I noticed that although the "Save EEPROM" setting is set to EEPROM retained, every time I load a sketch, the EEPROM is erased.
Is there any other setting that I have to do so the EEPROM is not cleared when programming attiny2313?
I'm using ATTinyCore library version 1.2.3 to program an Attiny2313. And I'm using as programmer an Arduino Nano: Arduino as ISP (ATTinyCore).
Arduino IDE version is 1.8.9.

![image](https://user-images.githubusercontent.com/40923207/56501766-51d9e180-64e6-11e9-95b3-d09dd59dd68d.png)

**Comment by liebman** [comment]
That value is actually a fuse setting.  You need to "burn bootloader" to apply fuse settings for them to be applied.

**Comment by jhmluna** [comment]
Thank you very much! It worked.
