### ISSUE TITLE
On some versions of Arduino IDE, cached cores exceed MAX_PATH on windows

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/ATTinyCore#313]
http://forum.arduino.cc/index.php?topic=605303.15

**Comment by SpenceKonde** [comment]
Fixed by ce8cde8d366443a274100abdd3a4a1e741934939 which shortens the names used internally (but not user-facing) for these options.

**Comment by sleemanj** [comment]
> http://forum.arduino.cc/index.php?topic=612754

Wrong link?

**Comment by SpenceKonde** [comment]
http://forum.arduino.cc/index.php?topic=605303 is the correct link, oops

**Comment by sleemanj** [comment]
FWIW

I think this was probably "fixed" (reduced chance of it happening) in 1.8.6 when the shipped arduino-builder was updated to 1.4.0

https://www.arduino.cc/en/Main/ReleaseNotes
https://github.com/arduino/arduino-builder/pull/249
https://github.com/arduino/Arduino/issues/6751 (and issues referencing it)

**Comment by SpenceKonde** [comment]
Reverted these changes until I can figure out what to do so that someone syncing from github doesn't get something that won't work with automated builds.
