### ISSUE TITLE
Software I2C Master doesn't work on ATTINY828

### ISSUE THREAD

**Issue by MatCat** [SpenceKonde/ATTinyCore#338]
I tried to use I2C on ATTINY828, doesn't work, seems that a function is called deep in the library that is disabled by a #define.

**Comment by SpenceKonde** [comment]
Can you let me know what error you're getting? And the code that generates it?

Also - when you say Software I2C Master - are you referring to the builtin one via Wire.h? That is what you should be using - with ATTinyCore (at least recent versions of it) there is no need to use the SoftwareI2CMaster library

**Comment by MatCat** [comment]
No error, just hangs the MCU.  I have tried the built in Wire,h, I tried TinyWireM, and I tried SoftI2CMaster, none of them work,

**Comment by MatCat** [comment]
ERr sorry, hangs the MCU with the other libraries, with the built in wire it complains about a missing function,  C:\Users\MatCat\AppData\Local\Temp\ccgDQwDd.ltrans0.ltrans.o: In function `main':
<artificial>:(.text.startup+0x2c8): undefined reference to `TwoWire::begin()'

**Comment by SpenceKonde** [comment]
Hm, I can compile I2C master code using builtin Wire.h without issue. Can you post the code that's giving that error?

**Comment by MatCat** [comment]
It's got 2000 lines of code... but I did create a new blank project with just this, same issue:

#include <Arduino.h>
#include <Wire.h>

void setup() {
  // put your setup code here, to run once:
  Wire.begin();
}

void loop() {
  // put your main code here, to run repeatedly:
}

**Comment by MatCat** [comment]
I just did some research,  I don't think PlatformIO uses your library, I thought it did.

**Comment by SpenceKonde** [comment]
My guess is it *does* use my board package, just a very old version of it.....

**Comment by SpenceKonde** [comment]
Closed, since not a problem with the ATTinyCore in it's current incarnation, but with what is in platformIO.
