### ISSUE TITLE
disable or enable millis

### ISSUE THREAD

**Issue by Master811129** [SpenceKonde/ATTinyCore#343]
hello can you add an option to disable or enable millis like this core?
https://github.com/sleemanj/optiboot/blob/master/dists/README.md
thanks.

**Comment by Master811129** [comment]
did you add this?

**Comment by SpenceKonde** [comment]
Yes, it is in the github and will be available in 1.3.0 board manager release, which will happen within a few days (at the same time as 1.0.4 megaTinyCore
