### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by MCUdude** [SpenceKonde/ATTinyCore#35]
Some minor typos. use MHz instead of mhz, and kHz instead of khz. And for the tiny85, the lowest frequency available is 128kHz, not MHz ;)
![skjermbilde 2015-11-10 22 13 51](https://cloud.githubusercontent.com/assets/3238730/11076148/84191332-87f9-11e5-8811-b71a69be0d3e.png)

**Comment by SpenceKonde** [comment]
Thanks!
