### ISSUE TITLE
boards.txt attinyx5opti missing build.pllsettings

### ISSUE THREAD

**Issue by nonix** [SpenceKonde/ATTinyCore#350]
Hi guys, I am not an expert in this field, but could it be that settings for ATtiny45/85 (Optiboot) is missing configuration of build.pllsettings ?
This fails to build with Arduino IDE 1.8.9:
avr-g++: error: {build.pllsettings}: No such file or directory

exit status 1
Error compiling for board ATtiny45/85 (Optiboot).

After removing reference to build.pllsettings from build.extra_flags:
attinyx5opti.build.extra_flags={build.millis} -DNEOPIXELPORT=PORTB ~~{build.pllsettings}~~

It does compile, but I am not sure if all is correct :-) 
Thank you,
 N.

**Comment by SpenceKonde** [comment]
This bug was fixed with the 1.3.2 release, please update to that version of the core to resolve the issue.
