### ISSUE TITLE
DISABLEMILLIS should leave timer interrupt disabled

### ISSUE THREAD

**Issue by tikonen** [SpenceKonde/ATTinyCore#354]
Hi, 
I'm not very familiar with the code so I might misunderstood something but this looks like a bug.
I'm building for ATTiny2313 and my project crashes after enabling interrupts if I had disabled millis().
Workaround is to define dummy ISR handler 
```
#if defined(DISABLEMILLIS)
/* dummy handler */
SIGNAL(TIMER0_OVF_vect)
{
}
#endif
```
Probably the init function in the ATTinyCore\avr\cores\tiny\wiring.c should leave timer interrupt disabled if the define is set. My guess is that code will fault because the ISR handler is not defined at least on ATTiny2313 target.

Thank you for the great project!

**Comment by SpenceKonde** [comment]
Will investigate why the interrupt is getting enabled; it should not be.

**Comment by SpenceKonde** [comment]
Thanks for reporting this bug.
