### ISSUE TITLE
Arduino 1.8.10 Board Manager doesn't show repository

### ISSUE THREAD

**Issue by phisp** [SpenceKonde/ATTinyCore#361]
It works with Arduino IDE 1.8.5 but not with Arduino IDE 1.8.10.

**Comment by SpenceKonde** [comment]
I cannot reproduce this problem. I suspect this is an IDE/configuration issue; would suggest asking in https://forum.arduino.cc/index.php?board=2.0

**Comment by phisp** [comment]
Thanks very much for your work and help.

My mistake was "Tools -> Manage Libraries..."
is something different than "Tools -> Board: -> Boards Manager..."

The differences are explained here:
https://forum.arduino.cc/index.php?topic=620661.0
Thanks again
