### ISSUE TITLE
Error in clock speed list for x5 series

### ISSUE THREAD

**Issue by vk2amv** [SpenceKonde/ATTinyCore#38]
In the Arduino IDE, when I select Board: "ATTiny x5 Series" there is an error in the clock selection list.

For the slowest speed instead of showing "128 kHz (Internal)", it has "128 mhz (Internal)".

I don't know if the error is only in the listing, or if it will effect code too as I don't have an x5 chip to double check.

I am using Arduino IDE version 1.6.6 on Windows 10

**Comment by SpenceKonde** [comment]
Thanks, already fixed with https://github.com/SpenceKonde/ATTinyCore/commit/344177f70617654c2b1e16f29e5ef06196ff06fe

It was just a typo - it was 128kHz.
