### ISSUE TITLE
Pinout Picture generator/update?

### ISSUE THREAD

**Issue by a7hybnj2** [SpenceKonde/ATTinyCore#382]
Missing some pinout pictures for SMD versions. I would be more than happy to provide the pictures but I was hoping the pretty scheme you currently use is some kind of generated image.

Can you point me toward how to make the pinout pictures so I can add some SMD updates to your repo.

**Comment by SpenceKonde** [comment]
The minigames are made by hans/@mcudude - I do not know if he has tooling
to generate them or has existing files that he modifies.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by MCUdude** [comment]
I don't have a pinout pic generator, it's actually as stupid as a Keynote project where everything is treated as figures. Not very elegant and pretty time-consuming. But the result itself looks quite nice though.

What specific SMD footprints are you missing? I'll see if I can find some time to make some more

**Comment by a7hybnj2** [comment]
The one I am currently using is [ATTiny84](http://ww1.microchip.com/downloads/en/DeviceDoc/8183S.pdf) in the `QFN/MLF/VQFN` package. Luckily its probabley one of the easiest to makeup since there are only 20pins and 7 are DNC. Thanks for taking a look.

**Comment by MCUdude** [comment]
@SpenceKonde can you post a list of the chips you'd like pinouts for, and what package?

**Comment by MCUdude** [comment]
Is this OK?
<img width="696" alt="Skjermbilde 2020-02-09 22 54 30" src="https://user-images.githubusercontent.com/3238730/74110729-4055e900-4b8f-11ea-8f8f-746934dbd43d.png">

**Comment by a7hybnj2** [comment]
That certainly covers what I wanted. I already printed it out for my binder. Thanks.

**Comment by MCUdude** [comment]
You can print it in landscape mode? as you can see, the "old" one above is just as long.

**Comment by a7hybnj2** [comment]
![Image 4](https://user-images.githubusercontent.com/36831279/74111139-59937100-4b60-11ea-8f89-12373d4dc197.jpeg)

As an example it doesn't look as good as the pinout for the ATTiny828 just because it is smaller on page.

Yes, I did print in landscape 😜

**Comment by MCUdude** [comment]
I get your point. This would have to be something @SpenceKonde will have to decide. The good thing about the pinout I just provided is that we can get both the DIP/SOIC and the QFN one in the same pinout picture. Another alternative is to make it similar to the ATtiny828 one. A third option is to make it like this:

![](https://camo.githubusercontent.com/4272e2903c4871740f84d6cd07a6a0ca1efd70df/68747470733a2f2f692e696d6775722e636f6d2f3430416e694b412e706e67)

**Comment by a7hybnj2** [comment]
Yea, totally what ever Spence wants to go with I am fine. I think these pinouts are great and I have them printed for all the AVR chips I use, not just the attinycore ones.

I like how you did the atmega324pb's with the 3 different pinout numbering schemes with 3 different pictures. So, I would be happy if the DIP and QFNs were separate images. But, again I am already happy so whatever Spence wants to go with.

Would be cool if you made a MCUdude Pinout generator somehow.

**Comment by MCUdude** [comment]
> Would be cool if you made a MCUdude Pinout generator somehow.

That would indeed be really nice, but I'm not really into that sort of stuff. Ideally, it should have been a website, but I don't know much about Javascript, HTML or web design in general. What I'll do instead is a monkeys work; doing all this manually using a program that's not really meant to be used for this...

For reference, heroes what the "ATtiny828 style" would look like:
<img width="662" alt="Skjermbilde 2020-02-09 23 48 41" src="https://user-images.githubusercontent.com/3238730/74111679-c7f32600-4b96-11ea-983b-a49d599c641d.png">

**Comment by a7hybnj2** [comment]
I updated my notebook to use the latest diagonal version. It looks pretty funny with how unbalanced it is but I like it.

**Comment by SpenceKonde** [comment]
Hmm, I think the one with both next to eachother looks better and strikes me as more readable, since all the text is horizontal.... I will put the other image into the repo, though. 

Thanks for the great work as always!
I wonder if there are any others that have alternate packages we haven't thought about... 

Leaving open because I am not going to deal with the images at this moment

**Comment by MCUdude** [comment]
> I wonder if there are any others that have alternate packages we haven't thought about...

I don't think I'll bother creating QFN versions for absolutely _all_ ATtinys, but I can make a few more.

I'm pretty much finished with:
* ATtiny25/45/85
* ATtiny24/44/84
* ATtiny441/841

Are there other chips that "_must_" have a QFN pinout pic as well?

**Comment by MCUdude** [comment]
@SpenceKonde it would be great if you'd answer...

> Are there other chips that "must" have a QFN pinout pic as well?

**Comment by SpenceKonde** [comment]
84 and related 841, and the 1634 all come in a QFN/MLF package, and I have plans working their way, slowly, to bring boards based on those to market, so those are, I think the priorities. 

The 861, 167, and 43 all have QFN versions, but they are so niche, I don't think they're worth spending time on. There is also an MLF-20 version of the 85, but nobody ever seems to talk about it because it's not much smaller than the SOIC-8.
