### ISSUE TITLE
Update EEPROM library

### ISSUE THREAD

**Issue by SukkoPera** [SpenceKonde/ATTinyCore#39]
This core's EEPROM library has lagged behind Arduino's. More and more sketches out there are using the newer methods (update(), put(), get()), and updating the library would make them more compatible with ATtiny's.

At a quick glance, the library shouldn't require many changes, it might even compile as-is.

**Comment by SpenceKonde** [comment]
Dang, I didn't even know that stuff had been added...

**Comment by SpenceKonde** [comment]
Need to benchmark compile size for simple operations and determine whether they can just be swapped out. The reason not to would if the new library has a larger overhead associated with it for the legacy calls. In that case, I'll pull it in, but call it EEPROM2

**Comment by SukkoPera** [comment]
Yeah, or you can just implement a few wrappers for the new functions, just to be compatible with the updated interface.

**Comment by SpenceKonde** [comment]
As I said, I haven't benchmarked compiled code size. If there is significant overhead, though, I expect that the overhead will be inherent to the new functionality, and not separable from it.
