### ISSUE TITLE
Issues with PWM using AnalogWrite() on ATtiny 1634

### ISSUE THREAD

**Issue by dtlepley** [SpenceKonde/ATTinyCore#402]
Hello,

I am using a 1634 with a 12MHz external clock and am experiencing a PWM frequency of 64Hz on one PWM output and 32Hz on another (channels 2 and 3 respectively).  Both channels are PWM driving a LED driver.  This is leading to a visible blinking of the 32Hz channel.  Attached are the scope pictures of the two drive channels.
![32 vs 64Hz](https://user-images.githubusercontent.com/41594161/82164882-db421b80-9880-11ea-8453-2bf803ff6bc9.jpg)

The MCU really only needs to read an input and or two and set the PWM frequency (brightness) accordingly, so no other critical timing tasks.  

Is this consistent with the behavior of the core?  What is the best path towards increasing the PWM frequency above the visible range?

-Dave

**Comment by SpenceKonde** [comment]
Did you forget to "burn bootloader" to set clock source? The pwm frequency
should be 12x that, which suggests that it is still running at 1 MHz . Per
docs and in keeping with conventions set by official cores, fuses are only
at on "burn bootloader", never on normal upload.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: spencekonde@gmail.com

**Comment by dtlepley** [comment]
Well now I feel stupid...I was programming directly with a USBtinyISP and totally brain
farted...I was pulling my hair out!

All working now.

Really appreciate the contribution of the ATtiny core and the support.

Thanks!
-Dave

**Comment by SpenceKonde** [comment]
Thanks! Closing.
