### ISSUE TITLE
I2C Support

### ISSUE THREAD

**Issue by kontakt** [SpenceKonde/ATTinyCore#41]
I'm trying to use your core with the ATTinyx8, which has hardware I2C lines that I plan to use for my project. Do you have an implementation for that in the works, or should I try and make one on my own and submit a pull request?

**Comment by SpenceKonde** [comment]
Sorry that took so long - I somehow missed this issue when you filed it, and didn't see it until today.

**Comment by kontakt** [comment]
Thanks! This will make things a lot simpler for one of my projects.
