### ISSUE TITLE
LTO with default -Os is way too agressive

### ISSUE THREAD

**Issue by sx107** [SpenceKonde/ATTinyCore#413]
LTO with -Os is probably way too agressive. Any way this can be adjusted other than turning size optimizaton or LTO off completely?

Where I encountered the problem:

So I have a sound generating project on attiny85 using timer0 for PWM output and timer1 for sample-rate interrupt with two main files: the .ino file and synth.h, synth.cpp.

The .ino file is relatively simple:

```
#include synth.h
void setup() {timers setup...}
void loop() {synthesis();}
```

In synth.cpp, the synthesis() function is defined, as well as the interrupt for the timer1, which pass information to each other using global variables:

```
uint8_t sample1, sample2;

ISR(TIMER1_COMPA_vect) {
OCR0A = sample1; OCR0B = sample2;
}

void synthesis() {sample1 = some calculation; sample2 = some calculation;}
```

Compiling with the standard -Os, LTO enabled this code does not work, making sample1, sample2, synthesis() volatile does not help. Flash size: 1196 bytes.
Discarding the sample1, sample2 link between the ISR and synthesis() by either moving the calculation to the ISR or simply assigning calculation result straight to OCR0A, OCR0B instead of sample1, sample2 in the synthesis() function does help. Flash size: 1308 bytes, but this is not the behaviour I wish to be implemented, since it makes the ISR way too long.

Compiling with -O0: Original code works, but the flash size is over 4kb.
Compiling with -Os, LTO disabled: original code works, but the flash size is increased to 1774 bytes.

**Comment by SpenceKonde** [comment]
Huh! That's very surprising - are you sure you're not stepping into the realm of undefined behavior unknowingly? I haven't heard of issue

Can you do "export compiled binary" with and without LTO enabled (as with all of my cores, this will generate the assembly listing in the sketch folder), and send the two assembly listings, as well as the full source for the sketch to spencekonde@gmail.com? I would like to take a look at these with the actual files in question... This would be the first time I've heard of LTO actually breaking things...

**Comment by sx107** [comment]
Same here, never heard of something like this. I'll contact you by e-mail, thanks for a quick reply.

**Comment by SpenceKonde** [comment]
analogValues isn't declared volatile, so the compiler concludes that it can never change and optimizes out synthesize entirely. What's surprising is that it doesn't do that without enabling LTO!
