### ISSUE TITLE
Doc error linking to x8 DIP pinout JPG

### ISSUE THREAD

**Issue by prandeamus** [SpenceKonde/ATTinyCore#438]
Documentation error

The current link to "x8 DIP Pin Mapping" from the home page is a 404
https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/extras/Pinout_x8_PU.jpg
But file is at
https://github.com/SpenceKonde/ATTinyCore/blob/master/avr/extras/Pinout_x8-PU.jpg
(dash vs underscore confusion)

Not a huge problem because the file obviously does exist, of course.

**Comment by SpenceKonde** [comment]
Thanks for reporting!
