### ISSUE TITLE
All timekeeping on ATtiny841, 441 is severely broken in 1.4.0

### ISSUE THREAD

**Issue by arlarson** [SpenceKonde/ATTinyCore#445]
Hi I have a ATTiny 841 that I'm programming using ATTiny Core 1.4.0. I'm having timing issues when I use the delay/micros functions in that they seem ~32 times faster than expected. If I put a delay of 1000ms the delay seems to only last ~31.5 ms as measured on my oscilloscope. My ATTiny 841 is using a 16 MHz external oscillator and I've set the "16 MHz (external)" option in the Arduino IDE and burned the bootloader.

**Comment by SpenceKonde** [comment]
Yes I know there is a serious issue of some sort of the 841 currently, once DxCore 1.0.0 is released this is next on my list. Downgrade to previous version in the meantime. 

Somehow this was missed during pre-release checks of 1.4.0

**Comment by SpenceKonde** [comment]
Thank you for figuring out more regarding exactly what that issue is - I had not gotten beyond being aware that blink seemed to be running many times too fast.

**Comment by arlarson** [comment]
No problem, I'll try downgrading to an older version of ATTinyCore for now. Thanks for the quick response!

**Comment by brendanmatkin** [comment]
I just came to say this same thing! It also happens at 8Mhz internal, 1Mhz internal, both at 3v3 and 5v. Although the times differences are different for each. I can do some further testing if you need @SpenceKonde - I have a scope and several types of 841 boards (both with and without 16Mhz crystals).

**Comment by SpenceKonde** [comment]
Fix is in github. I'd accidentally commented out the call to sei() to enable interrupts. Didn't realize it had the wacky effects you all were seeing (lessons learned)

**Comment by SpenceKonde** [comment]
Now to try to sort out why the new bootloader bricks MHET t88's

**Comment by SpenceKonde** [comment]
6a6453c6c45d61ab6466df1ea126b35a15134a0f was the fix

**Comment by brendanmatkin** [comment]
Awesome! Will test tonight or tomorrow!
