### ISSUE TITLE
Is it possible to swap the RX1 and TX1 pin around on ATTiny 841?

### ISSUE THREAD

**Issue by arlarson** [SpenceKonde/ATTinyCore#450]
Hi, so unfortunately I made a bit of a mistake when creating a prototype board and got the wiring of RX1 and TX1 pins on the ATTiny 841 backwards. Is it possible to swap these pins in software (i.e assign RX1 to package pin 9 and TX1 to package pin 8) or is this a hardware limitation?

**Comment by SpenceKonde** [comment]
Huh, somehow didn't see the notification, No, that is a hardware limitation, sorry - you could do software serial, but you are probably usingthe 841 because you know how much software serial sucks.

**Comment by SpenceKonde** [comment]
closing because not a defect in the core, will still respond (assuming I get the damned notification)
