### ISSUE TITLE
optiboot_attiny441_8000000L_ser1_int.hex: No such file or directory

### ISSUE THREAD

**Issue by MarcSN311** [SpenceKonde/ATTinyCore#454]
`optiboot_attiny441_8000000L_int.hex` and `optiboot_attiny441_8000000L_ser1.hex` are there, but `optiboot_attiny441_8000000L_ser1_int.hex` doesn't exist

**Comment by SpenceKonde** [comment]
This missing bootloader file (and a rather embarrassing number of others, plus a few missing from boards.txt. has been build and added. And a number of no-longer-supported specialty builds that were years-behind were removed.
