### ISSUE TITLE
OC0B missing from ATtiny2313/4313 pinout diagram

### ISSUE THREAD

**Issue by dasfdlinux** [SpenceKonde/ATTinyCore#460]
The pinout diagram for the ATtiny2313 is missing OC0B on port pin PD5 (physical pin 9 on the DIP package). Also, the summary for that chip says it has 3 PWM instead of 4, as shown in the database.

See pull request #459 which fixes the text summary, but not the picture.

**Comment by SpenceKonde** [comment]
@MCUdude - diagrams are your department :-)

**Comment by MCUdude** [comment]
@SpenceKonde here you go:
[Uploading ATtinyX323.zip…]()

**Comment by MCUdude** [comment]
Somehow the file didn't get uploaded. Here it is:

[ATtinyX323.zip](https://github.com/SpenceKonde/ATTinyCore/files/5278653/ATtinyX323.zip)

**Comment by dasfdlinux** [comment]
See pull request #461. The replacement image was a png, so I simply opened the file in paint and re-exported it as a jpg. This resulted in a file that was 140% the file size of the original, so maybe some compression was done on the original? Anyway, the pull is available if you would like to use it.

**Comment by dasfdlinux** [comment]
@SpenceKonde Do you need anything else from me for pull request #461?

**Comment by SpenceKonde** [comment]
Merged PR - was just flat out with other problems over past week. I can do that step myself, I just hadn't had a change to do even simple things lately, especially with people complaining over more serious issues. 

Thanks @MCUdude for the pinout images as always

**Comment by dasfdlinux** [comment]
Thanks! It's been one of those weeks over here too. I figured you were planning to fix the image sometime, but it was good to have something simple like this that I knew I could finish.
