### ISSUE TITLE
t85 reading ADC and using PB0 as output

### ISSUE THREAD

**Issue by Jose2059** [SpenceKonde/ATTinyCore#476]
When reading analog reads on A2 and A3 of ATTINY85, and reference INTERNAL2V56, pin PB0 is not available as digital OUTPUT. This is normal.
But when using the reference INTERNAL2V56NOBP, the analogRead() does not work.
If I use DEFAULT or INTERNAL, it works fine. Using INTERNAL2V56 works fine as well (PB0 not available). But using INTERNAL2V56NOBP analogRead() does not return a converted value.

**Comment by Jose2059** [comment]
It was a hardware issue.

**Comment by SpenceKonde** [comment]
Glad to hear it's sorted! Wasn't looking forward to investigating :-P
