### ISSUE TITLE
Micronucleus link broken in http://drazzy.com/package_drazzy.com_index.json

### ISSUE THREAD

**Issue by thomasonw** [SpenceKonde/ATTinyCore#505]
The referenced file:  "https://github.com/ArminJo/DigistumpArduino/raw/master/tools/micronucleus-2.0a4-win.zip"
no longer exits.  It has been updated:  https://github.com/ArminJo/DigistumpArduino/tree/master/tools

**Comment by SpenceKonde** [comment]
Sigh. See #465. When I have a chance to come back and make an interim fix (after DxCore 1.3.1 release), I will not make the same mistake again - the Micronucleus client binaries on which ATTinyCore depends will be hosted in a location which I control.

**Comment by SpenceKonde** [comment]
I was able to locate a copy of the deleted windows package (note that there are two **DIFFERENT** windows binaries distributed online, _with the same filename_, and _same file size, down to the byte_. But the text of the .inf file is not the same. Luckily I had a copy of the old one sitting in the staging subdirectory in one of my portable installations so I could re-release it with confidence that what I was releasing is the same
