### ISSUE TITLE
ATTINY2313 128b

### ISSUE THREAD

**Issue by thundercat337** [SpenceKonde/ATTinyCore#54]
I'm flashing an ATTINY2313 and its telling me that there is only 128b of storage. I believe that it has 2kb of storge. Is this an issue in the core or does it really only have 128b?

**Comment by SpenceKonde** [comment]
It has 2048 bytes of flash, 128 bytes of RAM. 

The Arduino IDE reports usage of both of these types of memory upon compiling. Can you post the output you're seeing?

**Comment by thundercat337** [comment]
Sorry I was mistaken! I am getting the full 2kb of storge.  But thanks for the quick reply!

**Comment by SpenceKonde** [comment]
No problem, glad it's working :-)
