### ISSUE TITLE
MH-ET ATtiny88  - LED_BUILTIN on pin0 / PD0 missing in pins_arduino.h

### ISSUE THREAD

**Issue by ArminJo** [SpenceKonde/ATTinyCore#554]
The line
`#define LED_BUILTIN 0`
is missing in pins_arduino.h.
I just verified the connection on my MH-ET Attiny board 😀

**Comment by SpenceKonde** [comment]
This has already been fixed for 2.0.0. No further changes are being made to the 1.5.x branch.
https://github.com/SpenceKonde/ATTinyCore/blob/CombineTheCores/avr/variants/tinyX8_MH/pins_arduino.h
