### ISSUE TITLE
tinyNeoPixel: ColorHSV and gamma32 unimplemented

### ISSUE THREAD

**Issue by stonehippo** [SpenceKonde/ATTinyCore#600]
I wanted to use `ColorHSV()` and `gamma32()` with the tinyNeoPixel/tinyNeoPixel_Static libraries.

I thought they were available (they show up in the library header), but when trying to use them, I got an ld error about an undefined reference, which lead me to peek into the implementation, and sure enough, they're not there.

I assume these were defined for compatibility with the Adafruit_NeoPixel library. Any particular reason they're not implemented? If not, would a PR to include them be welcome?

**Comment by stonehippo** [comment]
I see that they've been implemented in megaTinyCore. Maybe I can just port those over.

**Comment by SpenceKonde** [comment]
Yeah I just hadn't gotten around to poetyongvthem to here it was on list
for the long delayed 2.
0.0

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by stonehippo** [comment]
Got it (and thanks for all the work you do on this and megaTinyCore!). If I can find time in the next couple of days, I'll shoot you a PR.

**Comment by SpenceKonde** [comment]
thanks, - the branch to pr to is 2.0.0-dev, 
NOT master. (note that nothing compiles over there due to lack of boards.txt - that'sthe next phase.

**Comment by SpenceKonde** [comment]
These are in v2.0.0-dev which is now available for public testing.
