### ISSUE TITLE
unable to upload Core

### ISSUE THREAD

**Issue by baritonomarchetto** [SpenceKonde/ATTinyCore#613]
Sorry for the dumb question, but I am having some issue installing the core using the board manager.
I am following step-by-step the (two lines of) instructions, but the board is not shown and then cannot be installed.
I am using IDE 1.8.16

Any clue on what I am possibly doing wrong? :)

thanks in advance for the help!

**Comment by hmeijdam** [comment]
https://docs.arduino.cc/foundations/programming/cores

scroll down to "How to install a third party core"

**Comment by baritonomarchetto** [comment]
Thank you for the answer. Those instructions are almost the same reported in this repo. I have the URL specified, but the Core package is not listed so it cannot be installed. 

I am likely missing something stupid here, I know, but I cannot see what :(

**Comment by baritonomarchetto** [comment]
Ok, solved! I was looking under library manager, not board manager.

Sorry and thanks!

**Comment by SpenceKonde** [comment]
Glad it's working
