### ISSUE TITLE
Board mgr fails to install on Arduino 1.8.16

### ISSUE THREAD

**Issue by fxframes** [SpenceKonde/ATTinyCore#621]
Trying to install ATTinyCore 1.5.2 on Arduino 1.8.16 through the Board Mgr gives an error.

Error downloading https://azduino.com/bin/micronucleus/micronucleus-cli-2.5-azd1b-i686-mingw32.zip

**Comment by prandeamus** [comment]
If you put that URL into the browser, you'll see the HTTPS cert expired a few hours ago. (Edit - I mean for azduino)

**Comment by SpenceKonde** [comment]
It is fixed.  I hate having to renew so often, and I've tried automating it without success.
