### ISSUE TITLE
Is it possible to emulate multiple I2C slaves in a single ATtiny841 chip?

### ISSUE THREAD

**Issue by uugear** [SpenceKonde/ATTinyCore#627]
Hello,
I wonder if it is possible to emulate multiple I2C slaves (with different addresses) in a single ATtiny841 chip?
If it can not be done by using the WireS library, could you shed some lights on how this can be achieved? Any idea/advice will be appreciated. Thank you in advance!

**Comment by SpenceKonde** [comment]
WireS is actually built into the included Wire library when used in slave mode.

It looks like you can just set `TWSAM` to the desired value before calling Wire.begin(). The tricky part is that there's no provision in the Wire API to support that. We did that over on megaTinyCore/DxCore, but the changes do not directly port as this is a very different version of the peripheral from what the modern AVRs use.

See section 20.5.5 of the datasheet:
```
TWSAM – TWI Slave Address Mask Register
 Bits 7:1 – TWSAM[7:1]: TWI Address Mask
These bits can act as a second address match register, or an address mask register, depending on the TWAE setting.
If TWAE is set to zero, TWSAM can be loaded with a 7-bit slave address mask. Each bit in TWSAM can mask (disable)
the corresponding address bit in the TWSA register. If the mask bit is one the address match between the incoming
address bit and the corresponding bit in TWSA is ignored. In other words, masked bits will always match.
If TWAE is set to one, TWSAM can be loaded with a second slave address in addition to the TWSA register. In this
mode, the slave will match on 2 unique addresses, one in TWSA and the other in TWSAM.
 Bit 0 – TWAE: TWI Address Enable
By default, this bit is zero and the TWSAM bits acts as an address mask to the TWSA register. If this bit is set to one, the
slave address match logic responds to the two unique addresses in TWSA and TWSAM
```
