### ISSUE TITLE
Port/Implement wire timeout

### ISSUE THREAD

**Issue by Strat00s** [SpenceKonde/ATTinyCore#636]
Would it be possible to add a timeout, just like the ArduinoCore-avr wire added last year? So that when a slave device loses power (but is still connected to SDA and SCL) it will timeout after a specified time and not loop forever.

https://github.com/arduino/ArduinoCore-avr/commit/deea9293201dbab724b6b0519c35ddba3e6b92d9

**Comment by SpenceKonde** [comment]
https://github.com/SpenceKonde/ATTinyCore/pull/618

We already have a PR for this; it will be in 2.0.0  (except on parts  that have to use software I2C master like the 841. I do not think I could get a timeout working on that without a complete reimplementation of the software I2C.
