### ISSUE TITLE
Where in the repo should part-specific documentation go? 

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/ATTinyCore#64]
For now am putting in ChipDocs in the root - but is there a better place to put that sort of thing?

@per1234, I'm looking at you ;-)

**Comment by per1234** [comment]
The problem with putting it in the root is that it is seen as a different architecture by the IDE so after doing a manual installation when you open/close Boards Manager you get the warning:
```
Could not find boards.txt in E:\arduino\hardware\ATTinyCore-master\ChipInfo. Is it pre-1.5?
```
This doesn't actually break anything but it might cause some confusion for the users so I think it would be better to put the ChipDocs folder under the avr folder. The libraries specification recommends putting things like this in an extras folder(so it would be avr/extras/ChipDocs), that doesn't apply to cores but might be something to consider if there are eventually going to be multiple folders like ChipDocs just to keep them in one place.

**Comment by SpenceKonde** [comment]
Moved them to extras so it doesn't cause problems for manual installs.

/avr/extras/docs or having the files loose in /avr/extras/ could both work.

**Comment by SpenceKonde** [comment]
Okay, extras it is, should have closed this months ago..
