### ISSUE TITLE
ATTINY1634/Servo.h

### ISSUE THREAD

**Issue by regis44** [SpenceKonde/ATTinyCore#67]
During the compilation of "Servo" library with a ATTINY1634, there's an error on TIFR and TIMSK registers because of ATTINY1634 is simply not declared in "servo.cpp". 
Is it possible to modify and add the servo library in the ATTinyCore package ?

Thanks for your great job.

Régis.

**Comment by SpenceKonde** [comment]
Thanks for https://github.com/SpenceKonde/ATTinyCore/pull/68

I will merge it, but will leave this issue open until this is tested.

**Comment by SpenceKonde** [comment]
Re-open or create new issue if it doesn't work - thanks :-)
