### ISSUE TITLE
Adapt and merge ArduinoShrink ?

### ISSUE THREAD

**Issue by uski** [SpenceKonde/ATTinyCore#671]
Like many I am sure, I am running out of space flash very quickly.
I experimented with the ArduinoShrink library, and it seems that a lot of its optimizations can be applied to ATTinyCore. 

Unfortunately there need to be a few adjustments done, especially regarding the timer support.
But some other optimizations like Wiring optimizations seem like they would be a direct fit.

URL: https://github.com/nerdralph/ArduinoShrink

Any thoughts about integrating this ?

**Comment by SpenceKonde** [comment]
Where practical and viable without breaking compatibility with large volumesof existing code, many those techniques are already integrated into the core (more so in 2.0.0-dev branch). I don't go quite as hard as he does with the assembly, 

Another complication is the heterogeneous nature of the parts that ATTinyCore supports. The core conditionally compiles:
Four implementations of a serial port (hardware serial, LIN, and software serial via either TinySoftSerial or SoftwareSerial) 
Three completely separate implementations of Wire (USI, Hardware I2C, and Software I2C Master with hardware I2C slave) 
Two completely separate implementations of SPI.h
Millis timekeeping functions - on the three different Timer0's, and PWM, servo and Tone for the ~6 different timer1's
Some parts support the Micronucleus bootloader. (Over 250 Micronucleus bootloader binaries have beeen prepared for 2.0.0)
Most parts support Optiboot. ATTinCore is supporting 586 optiboot configurations (ie, 586 hex files) in 2.0.0
Every family of parts has it's own set of ADC quirks - most of them have a differential ADC, some of which have more features than others. Except of course for the x313, which doesn't have an ADC.

I will also note that 2.0,0 (which is nearing release and available for public testing) does include digitalReadFast/digitalWriteFast/pinModeFast/etc; - implemented in that way they do not break code which implicitly relies on digitalWrite being slower than most people realize, yet provide the same toolset. 2.0.0 has slashed the size of the HardwareSerial library, particularly on parts with two serial ports. TinySoftSerial has also been largely rewritten, and is smaller now. All remaining CBI/SBI abuse has been eliminated, and a series of efficiency improvements have gone into almost everything. 

There will be no wholesale import of something like this, the scale of the undertaking is impractical for a project like this.
