### ISSUE TITLE
MH ET Live attiny88 having default blinking LED but I cant make my PC recognize it what ever i do!! (SOLVED)

### ISSUE THREAD

**Issue by Abdulrahman-owayj** [SpenceKonde/ATTinyCore#673]
hi everyone, sorry if this isnt new but i didn't find any solutions yet.
i have the mh tiny attiny88 board, which has the blinking LED program as default. when i connect it via USB (data cable) to my pc it cant recognize it. it recognizes all other boards like esp32, esp 01 , Arduino uno.
i added the link in preferences but the PORT doesn't appear.

**Comment by SpenceKonde** [comment]
Have you also downloaded and installed the drivers?


Nothing is expected to show in ports menu, those devices are dugispark
like, they are uploaded to using that tool, direct via USB. No serial port
appears or is involved.
____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by Abdulrahman-owayj** [comment]
yes i successfully installed the drivers.

i didnt get the last part, do u mean i can upload programs using arduino IDE without choosing the port ?

if u recommend another IDE ill try it out

**Comment by SpenceKonde** [comment]
Yeah, select the micronucleus board definition and it will upload over USB
wand nothing that the computer sees as a serial port is involved.

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by Abdulrahman-owayj** [comment]
thanks for the fast response, i did as u said but it stuck at plug in the device, i plug it in many times after hitting compile but no luck

![image](https://user-images.githubusercontent.com/5675794/154998522-2fc90581-7840-43c2-bce0-a557f8b4a6d4.png)


i found tutorial online where they can see it as COM port and it upload successfully after plug in

![image](https://user-images.githubusercontent.com/5675794/154998512-934ccbd3-4cad-4711-94cc-7256ceaedbb5.png)

**Comment by Abdulrahman-owayj** [comment]
### **PROBLEM SOLVED**

i reinstalled bootloader micronucleus with zadig , as i understand it this program created a driver for my device and let PC recognize it.

for anyone who has the same problem (PC dont recognize MH-ET LIVE ATTINY88 and dont make sound when plugin)
use official drivers first if no luck try a program called zadig with the configuration for micronucleus.


![image](https://user-images.githubusercontent.com/5675794/155024959-7469e25b-04c2-4d88-a396-8679e55a176e.png)


i could not upload them here

### This is the outcome (port is still not showing)
![image](https://user-images.githubusercontent.com/5675794/155025659-f59f654b-8b1a-4c76-94e6-fd7737e2529b.png)
