### ISSUE TITLE
AT90S2313-10PI

### ISSUE THREAD

**Issue by ogogon** [SpenceKonde/ATTinyCore#678]
Greetings!

Can I compile code for AT90S2313 using this solution?

Ogogon.

**Comment by SpenceKonde** [comment]
No, this core supports only classic tinyAVR devices with at least 2k of Flash memort, it has nothing to do with the AT90 parts.  The pre-mega generation AVRs have been dead for a decade, amAdding support might actually not be terribly hard, but the real question is why? Even the tiny2313, which is one of the least compelling tinyAVR parts still in production, appears to be strictly better than the AT902313 that it was based on. Regardless of why it is being done, it is a job for someone else. I already maintain three cores and they are too much work already!

None of these parts have been compelling options  for like 20 years, and if I'm not mistaken the tiny2313 is pin compatible (and available with more flash). And I've still been recommending against it almost as long as I've been maintaining this core for it's poor featureset and high price relative to it's contemporaries. which are themselves similarly crushed by modern AVRs.
