### ISSUE TITLE
ATTiny85: unwanted Impact on analogout when using servo library of this project 

### ISSUE THREAD

**Issue by heinerolli** [SpenceKonde/ATTinyCore#687]
The PWM signal used for analog out (on PB4) has an offset  / is not properly controllable (*) as soon as I am using the servo library (on PB0 )

I checked that with 2 different servos and with and without independent powersources for servo and ATTiny

(*) My use case:
I am driving a motor with this analog out signal (PWM signal goes through low pass filter generating a 0 to 5 Volt signal); 
motor speed is proportional to analog out, starting at a threshold of 1 Volt where the motor does not yet turn - which used to correlate to a value of 60 for analogWrite. When using the Servo Library the Motor is already at 1/2 Speed at analogWrite (PB4, 60)

**Comment by SpenceKonde** [comment]
This is correct and expected behavior, A timer can run the servo library or it can be used for PWM. It cannot be used for both simultaneously. Not with readily predictable results at least.
