### ISSUE TITLE
v2.0.0 - can't compile for ATtiny861 with legacy pin mapping + USI on port A

### ISSUE THREAD

**Issue by jwarby** [SpenceKonde/ATTinyCore#689]
Hi - I've been trying to use the v2.0.0-dev version of this package instead of the published v1.5.2 as I'm trying to do something using SPI on USI port A pins because my project is already making use of one of the default port B USI pins.

If I try to compile with standard pin mapping with either USI option, I'm getting this:

```
/home/<me>/workspace/arduino/hardware/ATTinyCore/avr/cores/tiny/Arduino.h:234:10: fatal error: pins_arduino.h: No such file or directory
 #include "pins_arduino.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board ATtiny861/461/261 (No Bootloader).
```

I can compile with legacy pin mapping + USI on port B, but if I try changing USI to port A, I get this instead:

```
avr-g++: error: {build.remap}: No such file or directory
exit status 1
Error compiling for board ATtiny861/461/261 (No Bootloader).
```

Other things that may be useful/of note:

- I had to change `version` from the interpolated string to a hardcoded value (`version=2.0.0`) in `avr/platform.txt` because I was getting "panic: no major version found"
- My settings are:
  - Board: ATtiny861 no bootloader
  - Chip: ATtiny861
  - everything else default except as mentioned above
- My Arduino IDE version is 1.8.19
- I'm using an Arduino as ISP to program (probably not relevant as not even compiling in this instance)
- I was previously able to compile and successfully upload this particular sketch with v1.5.2

Appreciate any help you could provide and do let me know if you need any more info from me in order to debug.

**Comment by SpenceKonde** [comment]
* no major version found is a bug that I have not been able to comprehend and which appears to lie in the IDE, and does not always seem to be correlated to what is being compiled for. It is incredibly frustrating, and I have no idea how to solve it other than working around it with an older version of the IDE. 
The build.remap error should be straightforward to resolve, I think I'm missing definitions for it in the boards.txt generation code for that part. I'm wondering why the other error is coming about though, it shouldn't be, and makes me wonder if the boards.txt is not getting the right value for the variant... I may have fixed this and not committed the changes yet.
