### ISSUE TITLE
#include SPI.h cant compile with ATTiny24

### ISSUE THREAD

**Issue by seagatecm** [SpenceKonde/ATTinyCore#70]
Hi  everyone!
i download the tinycore version 1.1.1 and choose chip ATTiny24. And my arduino IDE version 1.6.7.
i add the `#include <ISP.h>` at the top of scratch and compile it with command ctrl-r. It reports Error:

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In member function 'void SPISettings::init_AlwaysInline(uint32_t, uint8_t, uint8_t)':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:146:16: error: 'SPE' was not declared in this scope

     spcr = _BV(SPE) | _BV(MSTR) | ((bitOrder == LSBFIRST) ? _BV(DORD) : 0) |

                ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:146:27: error: 'MSTR' was not declared in this scope

     spcr = _BV(SPE) | _BV(MSTR) | ((bitOrder == LSBFIRST) ? _BV(DORD) : 0) |

                           ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:146:65: error: 'DORD' was not declared in this scope

     spcr = _BV(SPE) | _BV(MSTR) | ((bitOrder == LSBFIRST) ? _BV(DORD) : 0) |

                                                                 ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static void SPIClass::beginTransaction(SPISettings)':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:203:5: error: 'SPCR' was not declared in this scope

     SPCR = settings.spcr;

     ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:204:5: error: 'SPSR' was not declared in this scope

     SPSR = settings.spsr;

     ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static uint8_t SPIClass::transfer(uint8_t)':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:209:5: error: 'SPDR' was not declared in this scope

     SPDR = data;

     ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:217:14: error: 'SPSR' was not declared in this scope

     while (!(SPSR & _BV(SPIF))) ; // wait

              ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:217:25: error: 'SPIF' was not declared in this scope

     while (!(SPSR & _BV(SPIF))) ; // wait

                         ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static uint16_t SPIClass::transfer16(uint16_t)':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:223:11: error: 'SPCR' was not declared in this scope

     if (!(SPCR & _BV(DORD))) {

           ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:223:22: error: 'DORD' was not declared in this scope

     if (!(SPCR & _BV(DORD))) {

                      ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:224:7: error: 'SPDR' was not declared in this scope

       SPDR = in.msb;

       ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:226:16: error: 'SPSR' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:226:27: error: 'SPIF' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                           ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:230:16: error: 'SPSR' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:230:27: error: 'SPIF' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                           ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:233:7: error: 'SPDR' was not declared in this scope

       SPDR = in.lsb;

       ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:235:16: error: 'SPSR' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:235:27: error: 'SPIF' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                           ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:239:16: error: 'SPSR' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:239:27: error: 'SPIF' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                           ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static void SPIClass::transfer(void*, size_t)':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:247:5: error: 'SPDR' was not declared in this scope

     SPDR = *p;

     ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:250:16: error: 'SPSR' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:250:27: error: 'SPIF' was not declared in this scope

       while (!(SPSR & _BV(SPIF))) ;

                           ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:255:14: error: 'SPSR' was not declared in this scope

     while (!(SPSR & _BV(SPIF))) ;

              ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:255:25: error: 'SPIF' was not declared in this scope

     while (!(SPSR & _BV(SPIF))) ;

                         ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static void SPIClass::setBitOrder(uint8_t)':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:292:31: error: 'SPCR' was not declared in this scope

     if (bitOrder == LSBFIRST) SPCR |= _BV(DORD);

                               ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:292:43: error: 'DORD' was not declared in this scope

     if (bitOrder == LSBFIRST) SPCR |= _BV(DORD);

                                           ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:293:10: error: 'SPCR' was not declared in this scope

     else SPCR &= ~(_BV(DORD));

          ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:293:24: error: 'DORD' was not declared in this scope

     else SPCR &= ~(_BV(DORD));

                        ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static void SPIClass::setDataMode(uint8_t)':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:298:5: error: 'SPCR' was not declared in this scope

     SPCR = (SPCR & ~SPI_MODE_MASK) | dataMode;

     ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static void SPIClass::setClockDivider(uint8_t)':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:303:5: error: 'SPCR' was not declared in this scope

     SPCR = (SPCR & ~SPI_CLOCK_MASK) | (clockDiv & SPI_CLOCK_MASK);

     ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:304:5: error: 'SPSR' was not declared in this scope

     SPSR = (SPSR & ~SPI_2XCLOCK_MASK) | ((clockDiv >> 2) & SPI_2XCLOCK_MASK);

     ^

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static void SPIClass::attachInterrupt()':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:309:42: error: 'SPCR' was not declared in this scope

   inline static void attachInterrupt() { SPCR |= _BV(SPIE); }

                                          ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:309:54: error: 'SPIE' was not declared in this scope

   inline static void attachInterrupt() { SPCR |= _BV(SPIE); }

                                                      ^

In file included from C:\Users\chenmin\Documents\arduino-1.6.5-r2\examples\01.Basics\Blink\Blink.ino:1:0:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h: In static member function 'static void SPIClass::detachInterrupt()':

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:310:42: error: 'SPCR' was not declared in this scope

   inline static void detachInterrupt() { SPCR &= ~_BV(SPIE); }

                                          ^

In file included from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\io.h:99:0,

                 from c:\users\chenmin\documents\arduino-1.6.7\hardware\tools\avr\avr\include\avr\pgmspace.h:88,

                 from C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\cores\tiny/Arduino.h:8,

                 from sketch\Blink.ino.cpp:1:

C:\Users\chenmin\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.1.1\libraries\SPI/SPI.h:310:55: error: 'SPIE' was not declared in this scope

   inline static void detachInterrupt() { SPCR &= ~_BV(SPIE); }

                                                       ^

exit status 1
编译有误。
java.lang.InterruptedException
java.lang.RuntimeException: java.lang.InterruptedException
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$23(ContributionManagerUI.java:145)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InterruptedException
	at cc.arduino.utils.network.FileDownloader.downloadFile(FileDownloader.java:211)
	at cc.arduino.utils.network.FileDownloader.download(FileDownloader.java:123)
	at cc.arduino.contributions.DownloadableContributionsDownloader.download(DownloadableContributionsDownloader.java:111)
	at cc.arduino.contributions.packages.ContributionInstaller.download(ContributionInstaller.java:330)
	at cc.arduino.contributions.packages.ContributionInstaller.downloadIndexAndSignature(ContributionInstaller.java:305)
	at cc.arduino.contributions.packages.ContributionInstaller.updateIndex(ContributionInstaller.java:283)
	at cc.arduino.contributions.packages.ui.ContributionManagerUI.lambda$onUpdatePressed$23(ContributionManagerUI.java:141)
	... 1 more

Please help.

**Comment by SpenceKonde** [comment]
Presumably you mean #include <SPI.h>

The standard SPI library is not supported on the ATTiny x4 series, as they do not have a hardware SPI peripheral. Thus, the compile fails when it finds that the registers it needs to manipulate are not present. 

The attiny x4 does have a hardware USI which can be used to implement SPI, but a different library is needed. The tinySPI library ( https://github.com/SpenceKonde/tinySPI ) should work, but I haven't tested it. However, if you have any other libraries that reference the SPI library, you'll have to modify those to use tinySPI instead. 
In a future release of this core I intend to address this problem by  replacing the stock SPI library with one that contains appropriate code for implementing SPI using hardware SPI or USI depending on which is available (as well as a replacement for wire that will use either I2C, USI, or a software implementation). This is tracked in this issue: https://github.com/SpenceKonde/ATTinyCore/issues/53
