### ISSUE TITLE
'NEOPIXELPORT' was not declared in this scope

### ISSUE THREAD

**Issue by ghost** [SpenceKonde/ATTinyCore#705]
When trying to compile the following sketch

```
#include <tinyNeoPixel_Static.h>
#define PIN 1
#define NUMPIXELS 4
byte pixels[NUMPIXELS * 3];
tinyNeoPixel strip = tinyNeoPixel(NUMPIXELS, PIN, NEO_GRB, pixels);

void setup() {
  pinMode(PIN, OUTPUT);
}

void loop() { }
```

I get the error:
```
/Users/r00/Documents/Arduino/libraries/tinyNeoPixel_Static/tinyNeoPixel_Static.cpp: In member function 'void tinyNeoPixel::show()':
/Users/r00/Documents/Arduino/libraries/tinyNeoPixel_Static/tinyNeoPixel_Static.cpp:137:8: error: 'NEOPIXELPORT' was not declared in this scope
   hi = NEOPIXELPORT |  pinMask;
        ^~~~~~~~~~~~
/Users/r00/Documents/Arduino/libraries/tinyNeoPixel_Static/tinyNeoPixel_Static.cpp:137:8: note: suggested alternative: 'NOT_A_PORT'
   hi = NEOPIXELPORT |  pinMask;
        ^~~~~~~~~~~~
        NOT_A_PORT
exit status 1
Error compiling for board ATtiny25/45/85.
```

I'm using the ATtiny85 board core [here](https://github.com/damellis/attiny). Is this a bug in the library (doubt it) or do I need to change my configuration?

**Comment by hmeijdam** [comment]
With AttinyCore it compiles just fine. So suggest you change to AttinyCore.

I am puzzled why you log an issue in for AttinyCore, while you are using a different core.

**Comment by sleemanj** [comment]
That damellis "core" should die a horrible death.  See so many people trying to use it with ATtinys.  It has no core in it, it's just a boards defintion to use the Arduino core and hope for the best.

**Comment by SpenceKonde** [comment]
A surprising number of prople do it, particularly with the recommended
_static versionThe reliance on the neopixelport define Iis gone in
2.0.0-dev branch, use version of that library from there (other parts pf
core are busted so can't release) but the new tinyneopixel (static and
normal) should be fully compatible between attinycore 2.0.0-dev and any
classic avr (and between megaTinyCore or dxcore (they share the same code
exactly for that lib) and any modern avr)

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***

**Comment by ghost** [comment]
I mistakenly linked the wrong core. I am using the ATTinyCore [here](https://github.com/SpenceKonde/ATTinyCore/tree/master/avr/libraries/tinyNeoPixel_Static). I get the same output on both cores though. Switching to the 2.0.0-dev branch resolves the compilation issue

**Comment by SpenceKonde** [comment]
Yeah, the released branch is pretty stale. I had to fork for development
because some of the changes were really cutting right to the heart of the
core (ex: release has two "cores" 2.0.0 has 1, release boards.txt was
written by hand which wasn't tenable etc

____________
Spence Konde
Azzy’S Electronics

New products! Check them out at tindie.com/stores/DrAzzy
GitHub: github.com/SpenceKonde
ATTinyCore: Arduino support for almost every ATTiny microcontroller
Contact: ***@***.***
