### ISSUE TITLE
Putting RSTDSBL among settings of x5, x4, and x41 parts

### ISSUE THREAD

**Issue by mistepien** [SpenceKonde/ATTinyCore#712]
It would be great to have an option to set RSTDSBL during upload to attinyx5 alongside with other options like i.a. B.O.D. Level.
There are cheap High Voltage Programmers so getting back working RESET is not a big issue. Such option would make
much easier using RESET as a regular input/output pin.

**Comment by SpenceKonde** [comment]
x5, x4, and x41 boards will get rstdsbl support added. 

The others will not unless someone can point me to an affordable or home-buildable HVPP reporogramming solution to reprogram them. If someone can, it will be added to all parts.
