### ISSUE TITLE
Report size deltas is busted and filling my email with errors/

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/ATTinyCore#716]
Doesanyoen even know what that action DOES?
It sounds real cool like I coould see how the size of examples changed as commits were made but therer  doesn't seem to beany way to get the data out!???

**Comment by SpenceKonde** [comment]
So it seems like this is just completely useless spammy action that generates no usable data, and that it hence is a [WOMBAT](https://www.acronymfinder.com/Waste-of-Money%2C-Bandwidth%2C-and-Time-(WOMBAT).html), and it should be shot dead and thrown over the fence into the neighbor's yard.

**Comment by designer2k2** [comment]
I purpose to turn it off for now, here i removed it: https://github.com/SpenceKonde/ATTinyCore/pull/734

**Comment by SpenceKonde** [comment]
Removed. Since... I NEVER KNEW HOW TO GET THE BLOODY REPORTS FROM THIS STUPID THING ANYWAY!
