### ISSUE TITLE
ATTiny1634 AREF

### ISSUE THREAD

**Issue by Smrtokvitek** [SpenceKonde/ATTinyCore#72]
Does anyone have tried external voltage reference on ATTiny1634? I am using LM4041 voltage reference (1.225 V) connected to AREF but I can read only 1023 (overflow?) and nothing else. When I use internal 1.1 V reference or 5 V (Vcc) reference it works. Input voltage I measure is lower than 1.225 V.

**Comment by SpenceKonde** [comment]
Huh. Interesting. I've had some odd (but different) issues related to AREF with internal reference. Have not tried with external reference.

**Comment by Smrtokvitek** [comment]
I will try to set the prescaler differently tomorrow. I am now using default way of reading from analog input via analogRead() and analogReference(EXTERNAL) as the ADC setup/init. I will let you know.

**Comment by Smrtokvitek** [comment]
so it turns out that I am an idiot. The minimum voltage that can be connected to AREF is 2 V. Sorry.

**Comment by SpenceKonde** [comment]
Well that would do it. 

That's a super lame limitation - where did you find that mentioned, by the way? I don't see it in the datasheet...

**Comment by Smrtokvitek** [comment]
table 24-9 External Voltage Reference minimum 2.0 V

**Comment by SpenceKonde** [comment]
Wow, what a great example of crystal clear documentation!
