### ISSUE TITLE
Clean up messy boards.txt file

### ISSUE THREAD

**Issue by MCUdude** [SpenceKonde/ATTinyCore#74]
Hey!
I was reading through my
have a

**Comment by MCUdude** [comment]
What happened here? My computer must have messed this up..

**Comment by SpenceKonde** [comment]
I was wondering the same thing. Is this not the same issue as the other issue you created at around the same time? I assumed it was...

**Comment by MCUdude** [comment]
There was supposed to be only one issue. It must have happened when I accidentally hit enter and created the issue before it was finished. #75 is the correct one
