### ISSUE TITLE
tinyNeoPixel's Fill command not working within v1.5.2 from Arduino's board manager. 

### ISSUE THREAD

**Issue by tuckerz** [SpenceKonde/ATTinyCore#766]
I see the function is in the header file for tinyNeoPixel_Static.h. However, I am getting a compile error that read: "'class tinyNeoPixel' has no member named 'fill'". I am attaching my setup to provide more detail. I don't think I have done anything wrong, but if I have, let me know and I'll retract this issue.... 

I am using version 2.1.0 of the new Arduino IDE:
![image](https://user-images.githubusercontent.com/100457623/236576614-fe748ab9-c2ca-4592-8f03-26f1d46fd83e.png)

I have installed ATTinyCore using the Arduino Board Manager after inserting the URL into the "additional boards manager URLs" field: 
![image](https://user-images.githubusercontent.com/100457623/236576723-f068dc83-ea4f-4093-8352-d1562c215ae6.png)

Version 1.5.2 of ATTinyCore is installed:
![image](https://user-images.githubusercontent.com/100457623/236576512-c1fceed4-4791-4abf-b0b9-0a618c3ad6a2.png)

And I get the following error:
![image](https://user-images.githubusercontent.com/100457623/236576493-9d13aa2a-ced2-4347-bb71-ef91c89cc728.png)

While using these board settings: 
![image](https://user-images.githubusercontent.com/100457623/236577049-f271a355-4f59-4f29-a66e-4843aacb7e90.png)

With this as my code: 
![image](https://user-images.githubusercontent.com/100457623/236577339-6251d3bc-3e15-479a-9f59-ac536aabac5f.png)
![image](https://user-images.githubusercontent.com/100457623/236577376-947240ab-f233-4024-afa4-f351cdec3156.png)
![image](https://user-images.githubusercontent.com/100457623/236577301-d9b83bbb-b6d2-435e-a1ed-e21f564e792c.png)
![image](https://user-images.githubusercontent.com/100457623/236577362-5bae94e4-ffe3-49ac-ae42-a343c4e2f187.png)
![image](https://user-images.githubusercontent.com/100457623/236577408-2e40fa13-8916-4f26-b5a6-f922900692cf.png)

**Comment by SpenceKonde** [comment]
Should work in 2.0.0-dev, it's just been so long since I've managed to get a release together that that library is old,
