### ISSUE TITLE
SPI Compile problems using T84 hardware

### ISSUE THREAD

**Issue by JohnOH** [SpenceKonde/ATTinyCore#786]
I am seeing the following compile error messages:

/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp: In static member function 'static void SPIClass::begin()':
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:259:22: error: 'USI_USCK_BIT' was not declared in this scope
     USI_CLOCK_DDR |= USI_USCK_BIT;   //set the USCK pin as output
                      ^~~~~~~~~~~~
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:259:22: note: suggested alternative: 'USI_CLOCK_BIT'
     USI_CLOCK_DDR |= USI_USCK_BIT;   //set the USCK pin as output
                      ^~~~~~~~~~~~
                      USI_CLOCK_BIT
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp: In static member function 'static void SPIClass::setDataMode(uint8_t)':
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:272:23: error: 'USI_USCK_BIT' was not declared in this scope
     USI_CLOCK_PORT |= USI_USCK_BIT;
                       ^~~~~~~~~~~~
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:272:23: note: suggested alternative: 'USI_CLOCK_BIT'
     USI_CLOCK_PORT |= USI_USCK_BIT;
                       ^~~~~~~~~~~~
                       USI_CLOCK_BIT
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:274:24: error: 'USI_USCK_BIT' was not declared in this scope
     USI_CLOCK_PORT &= ~USI_USCK_BIT;
                        ^~~~~~~~~~~~
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:274:24: note: suggested alternative: 'USI_CLOCK_BIT'
     USI_CLOCK_PORT &= ~USI_USCK_BIT;
                        ^~~~~~~~~~~~
                        USI_CLOCK_BIT
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp: In function 'byte reverse(byte)':
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:301:3: error: expected ')' before 'return'
   return(result);
   ^~~~~~
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:302:1: warning: no return statement in function returning non-void [-Wreturn-type]
 }
 ^
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp: In static member function 'static void SPIClass::applySettings(SPISettings)':
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:441:23: error: 'USI_USCK_BIT' was not declared in this scope
     USI_CLOCK_PORT |= USI_USCK_BIT;
                       ^~~~~~~~~~~~
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:441:23: note: suggested alternative: 'USI_CLOCK_BIT'
     USI_CLOCK_PORT |= USI_USCK_BIT;
                       ^~~~~~~~~~~~
                       USI_CLOCK_BIT
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:443:24: error: 'USI_USCK_BIT' was not declared in this scope
     USI_CLOCK_PORT &= ~USI_USCK_BIT;
                        ^~~~~~~~~~~~
/Users/johare/Documents/Arduino/hardware/ATTinyCore/avr/libraries/SPI/SPI.cpp:443:24: note: suggested alternative: 'USI_CLOCK_BIT'
     USI_CLOCK_PORT &= ~USI_USCK_BIT;
                        ^~~~~~~~~~~~
                        USI_CLOCK_BIT
``

**Comment by SpenceKonde** [comment]
This should be fixed now.
