### ISSUE TITLE
No serial on ATiny841  2.0.0 Codeline

### ISSUE THREAD

**Issue by ahshah** [SpenceKonde/ATTinyCore#787]
Description: I can flash updates via the IDE using optiboot, however I can't get anything to print to the serial monitor.

Bootloader UART Settings: TX: PA1 RX: PA2
Board settings:
![BoardSettings](https://github.com/SpenceKonde/ATTinyCore/assets/1134779/c05b1225-7852-4069-8e83-1085d1b60dc3)

Heres the code:
```
// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin LED_PIN as an output.
  Serial.begin(115200);
}

// the loop function runs over and over again forever
void loop() {
  Serial.println("on");
  delay(1000);  // wait for a second
  Serial.println("off");
  delay(1000);  // wait for a second
}
```
Here's the hook up, please note vcc and gnd connections are below the breadboard adapting board. The FTDI is a sparkfun model.

![rs_IMG_5364 heic](https://github.com/SpenceKonde/ATTinyCore/assets/1134779/903dbcb2-71ad-4baf-b780-9b66528469ce)

![rs_IMG_5363 heic](https://github.com/SpenceKonde/ATTinyCore/assets/1134779/81f1105e-cec3-408a-9999-bf4843c3d289)

**Comment by ahshah** [comment]
Codeline is currently on d670622155a459bf6e0757ac2032d0495bfa71b0: Correct issues with avrdude,conf.m make wiring readable

**Comment by ahshah** [comment]
The power and gnd rails read 3.3 v , and you can see 3.3v is soldered in the on the sparkfun FTDI controller

**Comment by SpenceKonde** [comment]
Curious indeed. There isn't much to go wrong in serial on 841 - but some changes were made so it is possible that something was broken, this is a very serious bug seeing as the whole reason this core was started was to get a tiny with 2 serial ports. 

Can you post the .lst and .map files that are created when you export compiled binary? I know it does listings, and I think maps are in too, the map is actually what I'm more interested in for once...

**Comment by ahshah** [comment]
Hi please find the requested resources attached. Codeline remaints at https://github.com/SpenceKonde/ATTinyCore/commit/d670622155a459bf6e0757ac2032d0495bfa71b0
[Serial.Attiny841.lst.map.zip](https://github.com/SpenceKonde/ATTinyCore/files/12316584/Serial.Attiny841.lst.map.zip)

**Comment by SpenceKonde** [comment]
I may have fixed this issue ( am in middle of a move, don't have access to hardware to test on atm)

**Comment by ahshah** [comment]
Confirmed, thanks for the fix! Confirmed working with 747d8533b747758be3bc4e91eb5c35a05057467c.
Could you narrow down what in the last few changes addressed this issue? Just for my edification.

**Comment by SpenceKonde** [comment]
It was that big commit with all those updates to the part-specific docs. That one also has a change to HardwareSerial (maybe several of the hardware serial files). It was failing to retain the register addresses. They were passed to the constructor and flushed down the toilet.

**Comment by SpenceKonde** [comment]
Thanks for testing!

**Comment by ahshah** [comment]
Hi, me again.
Seems like I'm getting corruption on the serial when running at slower speeds. Similar sketch, different result:

```
// the setup function runs once when you press reset or power the board
void setup() {
  Serial.begin(9600);
}

// the loop function runs over and over again forever
void loop() {
  Serial.println("on");
  delay(1000);  // wait for a second
  Serial.println("off");
  delay(1000);  // wait for a second
}
```

Results in gibberish-y output like so:
```
offonofCo                                     offon
         ofC
oofCoofCo   ofCon
oVH      HonoffConoff
   oHooffConCoffC
oHoCHonCofCoofCoC5VHonofCoCofVon
                  o
oHo                ofVon
   5
ofCooofCon
oVHoCofVHon5
            onC
```
Serial settings is 9600 @ 8N1
I've tested and reproduced this corruption on the following two commit points, but not inbetween.

`747d853`
`5508f88` 

Board settings as follows:
![BoardSettings](https://github.com/SpenceKonde/ATTinyCore/assets/1134779/1a848ae1-f91c-4bb1-b90c-fd879fb7e9f9)

**Comment by ahshah** [comment]
Hi it looks like this issue with baudrate has to do with internal oscillator variance, as similarly discussed here: 
https://forum.arduino.cc/t/attiny-841-serial-comms-baud-rate/343701

My attiny 841 is running off 5v so it seems that this is the likely culprit
