### ISSUE TITLE
Compile error when using SPI library

### ISSUE THREAD

**Issue by jagot** [SpenceKonde/ATTinyCore#795]
There is no `byte result;` in the `reverse` function anymore, preventing the compilation:
https://github.com/SpenceKonde/ATTinyCore/blob/1747efb854aba023332a5808bce5dee2b901fdc4/avr/libraries/SPI/SPI.cpp#L282-L302

I am not too good with assembly, but it seems that the reverse operation is performed in-place, and the result is then stored in `x`. I tried deleting the `return` statement, and the code compiles, but with a warning for missing `return` statement in a `non-void` function.

**Comment by sleemanj** [comment]
I believe `return(result)` shoudl be `return(x)`

**Comment by jagot** [comment]
Of course! That makes total sense.
