### ISSUE TITLE
Install error Linux

### ISSUE THREAD

**Issue by Eggberry** [SpenceKonde/ATTinyCore#826]
Got this when installing on Arduino 1.8.13 linux  
Error downloading https://azduino.com/bin/micronucleus/micronucleus-cli-2.5-azd1-x86_64-linux-gnu.tar.bz2

**Comment by hmeijdam** [comment]
If you look at the [list of issues](https://github.com/SpenceKonde/ATTinyCore/issues) and spend a few minutes to look at the latest issues you will see your problem and find a workaround.

**Comment by Eggberry** [comment]
https://github.com/SpenceKonde/ATTinyCore/issues/819#issuecomment-1828515189

**Comment by SteveC00k** [comment]
Just tried to do it manually. Its showing Certificate expiration warnings. :/
