### ISSUE TITLE
JSON link not working

### ISSUE THREAD

**Issue by ProAro** [SpenceKonde/ATTinyCore#864]
Hello Everyone,

After pasting the URL in preferences , I am getting the following error:
Some indexes could not be updated. Get "https://drazzy.com/package_drazzy.com_index.json": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: : http://drazzy.com/package_drazzy.com_index.json 
Can someone guide.
Thanks in Advance

**Comment by hmeijdam** [comment]
You could have guided yourself by reading through the issues #845,  #864 and #861

**Comment by ProAro** [comment]
Thank You Very much
