### ISSUE TITLE
Certificate expired for drazzy.com

### ISSUE THREAD

**Issue by ctnadovich** [SpenceKonde/ATTinyCore#869]
It appears this expired Wed, 29 May 2024 01:49:13 GMT

Consequently, this package index URL http://drazzy.com/package_drazzy.com_index.json  can be problematic.

**Comment by hmeijdam** [comment]
You can find the workaround when you read through the list of existing issues.

**Comment by ctnadovich** [comment]
Then you should remove this broken URL (and the suggestion to use it) from the installation instructions.

**Comment by hmeijdam** [comment]
I would, if I could, but the maintainer of this repository hes not been around for a while. I am just a user like yourself.

**Comment by arekm** [comment]
https://raw.githubusercontent.com/SpenceKonde/ReleaseScripts/master/package_drazzy.com_index.json
(but still problematic as it points to some not existing archives)

**Comment by VoidJuiceConcentrate** [comment]
Hello! Please fix the security certificate on your website drazzy.com. It appears to have expired on May 29th 2024. I believe you can use LetsEncrypt (https://letsencrypt.org/) for free short certs and cheap long term certs.

Alternatively, the .json file could be moved to github and you could operate out of there but I'm not sure how tenable that would be given the limits github imposes on data pulls.

**Comment by VoidJuiceConcentrate** [comment]
> https://raw.githubusercontent.com/SpenceKonde/ReleaseScripts/master/package_drazzy.com_index.json (but still problematic as it points to some not existing archives)

I'm going to use this workaround for now, but it seems this is partially broken and definitely not what the official instructions say to use. (Also I'm not a big fan of using workarounds for security verification issues so I hope the cert thing gets fixed soon)

**Comment by SpenceKonde** [comment]
fixed
