### ISSUE TITLE
Add support for the ATtiny26

### ISSUE THREAD

**Issue by SpenceKonde** [SpenceKonde/ATTinyCore#96]
Pretty sure this is an embarassingly easy addition.

**Comment by MCUdude** [comment]
It should be fairly easy, but a few register names i changes, becaud the X61 series is newer than the ATtiny26.

[AVR504: Migrating from ATtiny26 to
ATtiny261/461/861 ](http://www.atmel.com/Images/doc8026.pdf)

**Comment by SpenceKonde** [comment]
Not embarrassingly easy after all - they changed more than I realized. 

Deferring - this is not a priority chip to support.

**Comment by SpenceKonde** [comment]
Cleaning up issues. No plans to change this - it's an ancient chip with a miniscule amount of flash, considerable effort would be required to support it, and there are many other more pressing issues.
